// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: api/receipt/v1/receipt.proto

package receipt

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// =========================
// 创建收集表格式请求参数
// =========================
type CreateStyleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReceiptStyle  []*ReceiptStyleColumn  `protobuf:"bytes,1,rep,name=receipt_style,json=receiptStyle,proto3" json:"receipt_style,omitempty"` // 各行收集表格式汇总
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStyleReq) Reset() {
	*x = CreateStyleReq{}
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStyleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStyleReq) ProtoMessage() {}

func (x *CreateStyleReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStyleReq.ProtoReflect.Descriptor instead.
func (*CreateStyleReq) Descriptor() ([]byte, []int) {
	return file_api_receipt_v1_receipt_proto_rawDescGZIP(), []int{0}
}

func (x *CreateStyleReq) GetReceiptStyle() []*ReceiptStyleColumn {
	if x != nil {
		return x.ReceiptStyle
	}
	return nil
}

type ReceiptStyleColumn struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ReceiptColumnName string                 `protobuf:"bytes,1,opt,name=receiptColumnName,proto3" json:"receiptColumnName,omitempty"` // 单行收集栏标题
	SingleOption      int32                  `protobuf:"varint,2,opt,name=SingleOption,proto3" json:"SingleOption,omitempty"`          // 是否为单选：1=是，0=否，默认1
	OptionList        []string               `protobuf:"bytes,3,rep,name=optionList,proto3" json:"optionList,omitempty"`               // 可选项栏，如["离校", "不离校"] 或 ["upload_file"]
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReceiptStyleColumn) Reset() {
	*x = ReceiptStyleColumn{}
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiptStyleColumn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiptStyleColumn) ProtoMessage() {}

func (x *ReceiptStyleColumn) ProtoReflect() protoreflect.Message {
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiptStyleColumn.ProtoReflect.Descriptor instead.
func (*ReceiptStyleColumn) Descriptor() ([]byte, []int) {
	return file_api_receipt_v1_receipt_proto_rawDescGZIP(), []int{1}
}

func (x *ReceiptStyleColumn) GetReceiptColumnName() string {
	if x != nil {
		return x.ReceiptColumnName
	}
	return ""
}

func (x *ReceiptStyleColumn) GetSingleOption() int32 {
	if x != nil {
		return x.SingleOption
	}
	return 0
}

func (x *ReceiptStyleColumn) GetOptionList() []string {
	if x != nil {
		return x.OptionList
	}
	return nil
}

// =========================
// 返回参数
// =========================
type CreateStyleResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Code           int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                                            // 响应码
	Msg            string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`                                               // 提示信息
	ReceiptStyleId string                 `protobuf:"bytes,3,opt,name=receipt_style_id,json=receiptStyleId,proto3" json:"receipt_style_id,omitempty"` // 创建后的收集表格式ID
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateStyleResp) Reset() {
	*x = CreateStyleResp{}
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStyleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStyleResp) ProtoMessage() {}

func (x *CreateStyleResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStyleResp.ProtoReflect.Descriptor instead.
func (*CreateStyleResp) Descriptor() ([]byte, []int) {
	return file_api_receipt_v1_receipt_proto_rawDescGZIP(), []int{2}
}

func (x *CreateStyleResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateStyleResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CreateStyleResp) GetReceiptStyleId() string {
	if x != nil {
		return x.ReceiptStyleId
	}
	return ""
}

// ===============================
// 填收集表请求参数定义
// ===============================
type CreateReplyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoticeId      int32                  `protobuf:"varint,1,opt,name=notice_id,json=noticeId,proto3" json:"notice_id,omitempty"`            // 通知 ID
	ReceiptWrite  []*ReceiptWriteColumn  `protobuf:"bytes,2,rep,name=receipt_write,json=receiptWrite,proto3" json:"receipt_write,omitempty"` // 学生填写内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReplyReq) Reset() {
	*x = CreateReplyReq{}
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReplyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReplyReq) ProtoMessage() {}

func (x *CreateReplyReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReplyReq.ProtoReflect.Descriptor instead.
func (*CreateReplyReq) Descriptor() ([]byte, []int) {
	return file_api_receipt_v1_receipt_proto_rawDescGZIP(), []int{3}
}

func (x *CreateReplyReq) GetNoticeId() int32 {
	if x != nil {
		return x.NoticeId
	}
	return 0
}

func (x *CreateReplyReq) GetReceiptWrite() []*ReceiptWriteColumn {
	if x != nil {
		return x.ReceiptWrite
	}
	return nil
}

type ReceiptWriteColumn struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ReceiptColumnName string                 `protobuf:"bytes,1,opt,name=receiptColumnName,proto3" json:"receiptColumnName,omitempty"` // 对应老师格式单栏名称
	Options           []string               `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`                     // 学生选择的选项 / 填写内容 / 文件 URL
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReceiptWriteColumn) Reset() {
	*x = ReceiptWriteColumn{}
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiptWriteColumn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiptWriteColumn) ProtoMessage() {}

func (x *ReceiptWriteColumn) ProtoReflect() protoreflect.Message {
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiptWriteColumn.ProtoReflect.Descriptor instead.
func (*ReceiptWriteColumn) Descriptor() ([]byte, []int) {
	return file_api_receipt_v1_receipt_proto_rawDescGZIP(), []int{4}
}

func (x *ReceiptWriteColumn) GetReceiptColumnName() string {
	if x != nil {
		return x.ReceiptColumnName
	}
	return ""
}

func (x *ReceiptWriteColumn) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

// ===============================
// 返回参数定义
// ===============================
type CreateReplyResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Code           int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                                            // 状态码
	Msg            string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`                                               // 提示信息
	ReceiptWriteId string                 `protobuf:"bytes,3,opt,name=receipt_write_id,json=receiptWriteId,proto3" json:"receipt_write_id,omitempty"` // 填写记录 ID（唯一标识）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateReplyResp) Reset() {
	*x = CreateReplyResp{}
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReplyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReplyResp) ProtoMessage() {}

func (x *CreateReplyResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReplyResp.ProtoReflect.Descriptor instead.
func (*CreateReplyResp) Descriptor() ([]byte, []int) {
	return file_api_receipt_v1_receipt_proto_rawDescGZIP(), []int{5}
}

func (x *CreateReplyResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateReplyResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CreateReplyResp) GetReceiptWriteId() string {
	if x != nil {
		return x.ReceiptWriteId
	}
	return ""
}

// ========================
// 修改收集表填写内容请求参数定义
// ========================
type ChangeReceiptReplyReq struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ReceiptWriteId     string                 `protobuf:"bytes,1,opt,name=receipt_write_id,json=receiptWriteId,proto3" json:"receipt_write_id,omitempty"`             // 学生曾经填写的收集表 ID
	ReceiptWriteChange []*ReceiptWriteColumn  `protobuf:"bytes,2,rep,name=receipt_write_change,json=receiptWriteChange,proto3" json:"receipt_write_change,omitempty"` // 修改后的填写内容
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ChangeReceiptReplyReq) Reset() {
	*x = ChangeReceiptReplyReq{}
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeReceiptReplyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeReceiptReplyReq) ProtoMessage() {}

func (x *ChangeReceiptReplyReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeReceiptReplyReq.ProtoReflect.Descriptor instead.
func (*ChangeReceiptReplyReq) Descriptor() ([]byte, []int) {
	return file_api_receipt_v1_receipt_proto_rawDescGZIP(), []int{6}
}

func (x *ChangeReceiptReplyReq) GetReceiptWriteId() string {
	if x != nil {
		return x.ReceiptWriteId
	}
	return ""
}

func (x *ChangeReceiptReplyReq) GetReceiptWriteChange() []*ReceiptWriteColumn {
	if x != nil {
		return x.ReceiptWriteChange
	}
	return nil
}

// =========================
// 修改收集表填写内容响应参数定义
// =========================
type ChangeReceiptReplyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 返回状态码
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`    // 提示信息，如"修改成功"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeReceiptReplyResp) Reset() {
	*x = ChangeReceiptReplyResp{}
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeReceiptReplyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeReceiptReplyResp) ProtoMessage() {}

func (x *ChangeReceiptReplyResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeReceiptReplyResp.ProtoReflect.Descriptor instead.
func (*ChangeReceiptReplyResp) Descriptor() ([]byte, []int) {
	return file_api_receipt_v1_receipt_proto_rawDescGZIP(), []int{7}
}

func (x *ChangeReceiptReplyResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ChangeReceiptReplyResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_api_receipt_v1_receipt_proto protoreflect.FileDescriptor

const file_api_receipt_v1_receipt_proto_rawDesc = "" +
	"\n" +
	"\x1capi/receipt/v1/receipt.proto\x12\aReceipt\x1a\x1cgoogle/api/annotations.proto\"R\n" +
	"\x0eCreateStyleReq\x12@\n" +
	"\rreceipt_style\x18\x01 \x03(\v2\x1b.Receipt.ReceiptStyleColumnR\freceiptStyle\"\x86\x01\n" +
	"\x12ReceiptStyleColumn\x12,\n" +
	"\x11receiptColumnName\x18\x01 \x01(\tR\x11receiptColumnName\x12\"\n" +
	"\fSingleOption\x18\x02 \x01(\x05R\fSingleOption\x12\x1e\n" +
	"\n" +
	"optionList\x18\x03 \x03(\tR\n" +
	"optionList\"a\n" +
	"\x0fCreateStyleResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12(\n" +
	"\x10receipt_style_id\x18\x03 \x01(\tR\x0ereceiptStyleId\"o\n" +
	"\x0eCreateReplyReq\x12\x1b\n" +
	"\tnotice_id\x18\x01 \x01(\x05R\bnoticeId\x12@\n" +
	"\rreceipt_write\x18\x02 \x03(\v2\x1b.Receipt.ReceiptWriteColumnR\freceiptWrite\"\\\n" +
	"\x12ReceiptWriteColumn\x12,\n" +
	"\x11receiptColumnName\x18\x01 \x01(\tR\x11receiptColumnName\x12\x18\n" +
	"\aoptions\x18\x02 \x03(\tR\aoptions\"a\n" +
	"\x0fCreateReplyResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12(\n" +
	"\x10receipt_write_id\x18\x03 \x01(\tR\x0ereceiptWriteId\"\x90\x01\n" +
	"\x15ChangeReceiptReplyReq\x12(\n" +
	"\x10receipt_write_id\x18\x01 \x01(\tR\x0ereceiptWriteId\x12M\n" +
	"\x14receipt_write_change\x18\x02 \x03(\v2\x1b.Receipt.ReceiptWriteColumnR\x12receiptWriteChange\">\n" +
	"\x16ChangeReceiptReplyResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg2\xdd\x02\n" +
	"\aReceipt\x12h\n" +
	"\vCreateStyle\x12\x17.Receipt.CreateStyleReq\x1a\x18.Receipt.CreateStyleResp\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/receipt/write/create/style\x12i\n" +
	"\vCreateReply\x12\x17.Receipt.CreateReplyReq\x1a\x18.Receipt.CreateReplyResp\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/receipt/write/student/reply\x12}\n" +
	"\x12ChangeReceiptReply\x12\x1e.Receipt.ChangeReceiptReplyReq\x1a\x1f.Receipt.ChangeReceiptReplyResp\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/receipt/write/change/replyB,Z*ArgoNavisV1/Receipt/api/receipt/v1;receiptb\x06proto3"

var (
	file_api_receipt_v1_receipt_proto_rawDescOnce sync.Once
	file_api_receipt_v1_receipt_proto_rawDescData []byte
)

func file_api_receipt_v1_receipt_proto_rawDescGZIP() []byte {
	file_api_receipt_v1_receipt_proto_rawDescOnce.Do(func() {
		file_api_receipt_v1_receipt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_receipt_v1_receipt_proto_rawDesc), len(file_api_receipt_v1_receipt_proto_rawDesc)))
	})
	return file_api_receipt_v1_receipt_proto_rawDescData
}

var file_api_receipt_v1_receipt_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_receipt_v1_receipt_proto_goTypes = []any{
	(*CreateStyleReq)(nil),         // 0: Receipt.CreateStyleReq
	(*ReceiptStyleColumn)(nil),     // 1: Receipt.ReceiptStyleColumn
	(*CreateStyleResp)(nil),        // 2: Receipt.CreateStyleResp
	(*CreateReplyReq)(nil),         // 3: Receipt.CreateReplyReq
	(*ReceiptWriteColumn)(nil),     // 4: Receipt.ReceiptWriteColumn
	(*CreateReplyResp)(nil),        // 5: Receipt.CreateReplyResp
	(*ChangeReceiptReplyReq)(nil),  // 6: Receipt.ChangeReceiptReplyReq
	(*ChangeReceiptReplyResp)(nil), // 7: Receipt.ChangeReceiptReplyResp
}
var file_api_receipt_v1_receipt_proto_depIdxs = []int32{
	1, // 0: Receipt.CreateStyleReq.receipt_style:type_name -> Receipt.ReceiptStyleColumn
	4, // 1: Receipt.CreateReplyReq.receipt_write:type_name -> Receipt.ReceiptWriteColumn
	4, // 2: Receipt.ChangeReceiptReplyReq.receipt_write_change:type_name -> Receipt.ReceiptWriteColumn
	0, // 3: Receipt.Receipt.CreateStyle:input_type -> Receipt.CreateStyleReq
	3, // 4: Receipt.Receipt.CreateReply:input_type -> Receipt.CreateReplyReq
	6, // 5: Receipt.Receipt.ChangeReceiptReply:input_type -> Receipt.ChangeReceiptReplyReq
	2, // 6: Receipt.Receipt.CreateStyle:output_type -> Receipt.CreateStyleResp
	5, // 7: Receipt.Receipt.CreateReply:output_type -> Receipt.CreateReplyResp
	7, // 8: Receipt.Receipt.ChangeReceiptReply:output_type -> Receipt.ChangeReceiptReplyResp
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_receipt_v1_receipt_proto_init() }
func file_api_receipt_v1_receipt_proto_init() {
	if File_api_receipt_v1_receipt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_receipt_v1_receipt_proto_rawDesc), len(file_api_receipt_v1_receipt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_receipt_v1_receipt_proto_goTypes,
		DependencyIndexes: file_api_receipt_v1_receipt_proto_depIdxs,
		MessageInfos:      file_api_receipt_v1_receipt_proto_msgTypes,
	}.Build()
	File_api_receipt_v1_receipt_proto = out.File
	file_api_receipt_v1_receipt_proto_goTypes = nil
	file_api_receipt_v1_receipt_proto_depIdxs = nil
}
