// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: api/push/v1/push.proto

package push

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushCodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentIdList []string               `protobuf:"bytes,1,rep,name=student_id_list,json=studentIdList,proto3" json:"student_id_list,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`      // 消息类型/业务码
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"` // 推送的消息内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushCodeReq) Reset() {
	*x = PushCodeReq{}
	mi := &file_api_push_v1_push_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushCodeReq) ProtoMessage() {}

func (x *PushCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_push_v1_push_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushCodeReq.ProtoReflect.Descriptor instead.
func (*PushCodeReq) Descriptor() ([]byte, []int) {
	return file_api_push_v1_push_proto_rawDescGZIP(), []int{0}
}

func (x *PushCodeReq) GetStudentIdList() []string {
	if x != nil {
		return x.StudentIdList
	}
	return nil
}

func (x *PushCodeReq) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PushCodeReq) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PushReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 返回码（0 表示成功）
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 返回信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushReply) Reset() {
	*x = PushReply{}
	mi := &file_api_push_v1_push_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushReply) ProtoMessage() {}

func (x *PushReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_push_v1_push_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushReply.ProtoReflect.Descriptor instead.
func (*PushReply) Descriptor() ([]byte, []int) {
	return file_api_push_v1_push_proto_rawDescGZIP(), []int{1}
}

func (x *PushReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PushReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_push_v1_push_proto protoreflect.FileDescriptor

const file_api_push_v1_push_proto_rawDesc = "" +
	"\n" +
	"\x16api/push/v1/push.proto\x12\x04Push\x1a\x1cgoogle/api/annotations.proto\"c\n" +
	"\vPushCodeReq\x12&\n" +
	"\x0fstudent_id_list\x18\x01 \x03(\tR\rstudentIdList\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"9\n" +
	"\tPushReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2e\n" +
	"\x04Push\x12]\n" +
	"\x11PushCodeToStudent\x12\x11.Push.PushCodeReq\x1a\x0f.Push.PushReply\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/push/notice/code-messageB\x1eZ\x1cNotice/Push/api/push/v1;pushb\x06proto3"

var (
	file_api_push_v1_push_proto_rawDescOnce sync.Once
	file_api_push_v1_push_proto_rawDescData []byte
)

func file_api_push_v1_push_proto_rawDescGZIP() []byte {
	file_api_push_v1_push_proto_rawDescOnce.Do(func() {
		file_api_push_v1_push_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_push_v1_push_proto_rawDesc), len(file_api_push_v1_push_proto_rawDesc)))
	})
	return file_api_push_v1_push_proto_rawDescData
}

var file_api_push_v1_push_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_push_v1_push_proto_goTypes = []any{
	(*PushCodeReq)(nil), // 0: Push.PushCodeReq
	(*PushReply)(nil),   // 1: Push.PushReply
}
var file_api_push_v1_push_proto_depIdxs = []int32{
	0, // 0: Push.Push.PushCodeToStudent:input_type -> Push.PushCodeReq
	1, // 1: Push.Push.PushCodeToStudent:output_type -> Push.PushReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_push_v1_push_proto_init() }
func file_api_push_v1_push_proto_init() {
	if File_api_push_v1_push_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_push_v1_push_proto_rawDesc), len(file_api_push_v1_push_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_push_v1_push_proto_goTypes,
		DependencyIndexes: file_api_push_v1_push_proto_depIdxs,
		MessageInfos:      file_api_push_v1_push_proto_msgTypes,
	}.Build()
	File_api_push_v1_push_proto = out.File
	file_api_push_v1_push_proto_goTypes = nil
	file_api_push_v1_push_proto_depIdxs = nil
}
