// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: api/group/v1/group.proto

package group_check

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommonResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResp) Reset() {
	*x = CommonResp{}
	mi := &file_api_group_v1_group_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResp) ProtoMessage() {}

func (x *CommonResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_group_v1_group_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResp.ProtoReflect.Descriptor instead.
func (*CommonResp) Descriptor() ([]byte, []int) {
	return file_api_group_v1_group_proto_rawDescGZIP(), []int{0}
}

func (x *CommonResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CommonResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 班级信息
type ClassInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassId       string                 `protobuf:"bytes,1,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	ClassName     string                 `protobuf:"bytes,2,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	Check         bool                   `protobuf:"varint,3,opt,name=check,proto3" json:"check,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassInfo) Reset() {
	*x = ClassInfo{}
	mi := &file_api_group_v1_group_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassInfo) ProtoMessage() {}

func (x *ClassInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_group_v1_group_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassInfo.ProtoReflect.Descriptor instead.
func (*ClassInfo) Descriptor() ([]byte, []int) {
	return file_api_group_v1_group_proto_rawDescGZIP(), []int{1}
}

func (x *ClassInfo) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

func (x *ClassInfo) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *ClassInfo) GetCheck() bool {
	if x != nil {
		return x.Check
	}
	return false
}

// 学生信息
type StudentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	StudentName   string                 `protobuf:"bytes,2,opt,name=student_name,json=studentName,proto3" json:"student_name,omitempty"`
	Check         bool                   `protobuf:"varint,3,opt,name=check,proto3" json:"check,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentInfo) Reset() {
	*x = StudentInfo{}
	mi := &file_api_group_v1_group_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentInfo) ProtoMessage() {}

func (x *StudentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_group_v1_group_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentInfo.ProtoReflect.Descriptor instead.
func (*StudentInfo) Descriptor() ([]byte, []int) {
	return file_api_group_v1_group_proto_rawDescGZIP(), []int{2}
}

func (x *StudentInfo) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *StudentInfo) GetStudentName() string {
	if x != nil {
		return x.StudentName
	}
	return ""
}

func (x *StudentInfo) GetCheck() bool {
	if x != nil {
		return x.Check
	}
	return false
}

// 年级信息
type GradeLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GradeId       string                 `protobuf:"bytes,1,opt,name=grade_id,json=gradeId,proto3" json:"grade_id,omitempty"`
	Check         bool                   `protobuf:"varint,2,opt,name=check,proto3" json:"check,omitempty"`      // 是否勾选
	Subjects      []*SubjectInfo         `protobuf:"bytes,3,rep,name=subjects,proto3" json:"subjects,omitempty"` // 专业列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradeLevel) Reset() {
	*x = GradeLevel{}
	mi := &file_api_group_v1_group_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeLevel) ProtoMessage() {}

func (x *GradeLevel) ProtoReflect() protoreflect.Message {
	mi := &file_api_group_v1_group_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeLevel.ProtoReflect.Descriptor instead.
func (*GradeLevel) Descriptor() ([]byte, []int) {
	return file_api_group_v1_group_proto_rawDescGZIP(), []int{3}
}

func (x *GradeLevel) GetGradeId() string {
	if x != nil {
		return x.GradeId
	}
	return ""
}

func (x *GradeLevel) GetCheck() bool {
	if x != nil {
		return x.Check
	}
	return false
}

func (x *GradeLevel) GetSubjects() []*SubjectInfo {
	if x != nil {
		return x.Subjects
	}
	return nil
}

// 专业信息
type SubjectInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubjectName   string                 `protobuf:"bytes,1,opt,name=subject_name,json=subjectName,proto3" json:"subject_name,omitempty"`
	Check         bool                   `protobuf:"varint,2,opt,name=check,proto3" json:"check,omitempty"`    // 是否勾选
	Classes       []*ClassInfo           `protobuf:"bytes,3,rep,name=classes,proto3" json:"classes,omitempty"` // 班级列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubjectInfo) Reset() {
	*x = SubjectInfo{}
	mi := &file_api_group_v1_group_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectInfo) ProtoMessage() {}

func (x *SubjectInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_group_v1_group_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectInfo.ProtoReflect.Descriptor instead.
func (*SubjectInfo) Descriptor() ([]byte, []int) {
	return file_api_group_v1_group_proto_rawDescGZIP(), []int{4}
}

func (x *SubjectInfo) GetSubjectName() string {
	if x != nil {
		return x.SubjectName
	}
	return ""
}

func (x *SubjectInfo) GetCheck() bool {
	if x != nil {
		return x.Check
	}
	return false
}

func (x *SubjectInfo) GetClasses() []*ClassInfo {
	if x != nil {
		return x.Classes
	}
	return nil
}

// 班级完整信息（含学生）
type ClassFullInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GradeId       string                 `protobuf:"bytes,1,opt,name=grade_id,json=gradeId,proto3" json:"grade_id,omitempty"`
	SubjectName   string                 `protobuf:"bytes,2,opt,name=subject_name,json=subjectName,proto3" json:"subject_name,omitempty"`
	ClassId       string                 `protobuf:"bytes,3,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	ClassName     string                 `protobuf:"bytes,4,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	Students      []*StudentInfo         `protobuf:"bytes,5,rep,name=students,proto3" json:"students,omitempty"` // 班级学生
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassFullInfo) Reset() {
	*x = ClassFullInfo{}
	mi := &file_api_group_v1_group_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassFullInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassFullInfo) ProtoMessage() {}

func (x *ClassFullInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_group_v1_group_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassFullInfo.ProtoReflect.Descriptor instead.
func (*ClassFullInfo) Descriptor() ([]byte, []int) {
	return file_api_group_v1_group_proto_rawDescGZIP(), []int{5}
}

func (x *ClassFullInfo) GetGradeId() string {
	if x != nil {
		return x.GradeId
	}
	return ""
}

func (x *ClassFullInfo) GetSubjectName() string {
	if x != nil {
		return x.SubjectName
	}
	return ""
}

func (x *ClassFullInfo) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

func (x *ClassFullInfo) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *ClassFullInfo) GetStudents() []*StudentInfo {
	if x != nil {
		return x.Students
	}
	return nil
}

// 班级基本信息
type ClassBasicInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassId       string                 `protobuf:"bytes,1,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	ClassName     string                 `protobuf:"bytes,2,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	Check         bool                   `protobuf:"varint,3,opt,name=check,proto3" json:"check,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassBasicInfo) Reset() {
	*x = ClassBasicInfo{}
	mi := &file_api_group_v1_group_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassBasicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassBasicInfo) ProtoMessage() {}

func (x *ClassBasicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_group_v1_group_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassBasicInfo.ProtoReflect.Descriptor instead.
func (*ClassBasicInfo) Descriptor() ([]byte, []int) {
	return file_api_group_v1_group_proto_rawDescGZIP(), []int{6}
}

func (x *ClassBasicInfo) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

func (x *ClassBasicInfo) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *ClassBasicInfo) GetCheck() bool {
	if x != nil {
		return x.Check
	}
	return false
}

// 学生详情
type StudentDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GradeId       string                 `protobuf:"bytes,1,opt,name=grade_id,json=gradeId,proto3" json:"grade_id,omitempty"`
	SubjectName   string                 `protobuf:"bytes,2,opt,name=subject_name,json=subjectName,proto3" json:"subject_name,omitempty"`
	ClassId       string                 `protobuf:"bytes,3,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	StudentName   string                 `protobuf:"bytes,4,opt,name=student_name,json=studentName,proto3" json:"student_name,omitempty"`
	StudentId     string                 `protobuf:"bytes,5,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentDetail) Reset() {
	*x = StudentDetail{}
	mi := &file_api_group_v1_group_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentDetail) ProtoMessage() {}

func (x *StudentDetail) ProtoReflect() protoreflect.Message {
	mi := &file_api_group_v1_group_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentDetail.ProtoReflect.Descriptor instead.
func (*StudentDetail) Descriptor() ([]byte, []int) {
	return file_api_group_v1_group_proto_rawDescGZIP(), []int{7}
}

func (x *StudentDetail) GetGradeId() string {
	if x != nil {
		return x.GradeId
	}
	return ""
}

func (x *StudentDetail) GetSubjectName() string {
	if x != nil {
		return x.SubjectName
	}
	return ""
}

func (x *StudentDetail) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

func (x *StudentDetail) GetStudentName() string {
	if x != nil {
		return x.StudentName
	}
	return ""
}

func (x *StudentDetail) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

// 群组基本信息
type GroupInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	Category      int32                  `protobuf:"varint,3,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupInfo) Reset() {
	*x = GroupInfo{}
	mi := &file_api_group_v1_group_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInfo) ProtoMessage() {}

func (x *GroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_group_v1_group_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupInfo.ProtoReflect.Descriptor instead.
func (*GroupInfo) Descriptor() ([]byte, []int) {
	return file_api_group_v1_group_proto_rawDescGZIP(), []int{8}
}

func (x *GroupInfo) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupInfo) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *GroupInfo) GetCategory() int32 {
	if x != nil {
		return x.Category
	}
	return 0
}

// 个人群组/职位群组成员
type PersonItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	StudentName   string                 `protobuf:"bytes,2,opt,name=student_name,json=studentName,proto3" json:"student_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonItem) Reset() {
	*x = PersonItem{}
	mi := &file_api_group_v1_group_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonItem) ProtoMessage() {}

func (x *PersonItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_group_v1_group_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonItem.ProtoReflect.Descriptor instead.
func (*PersonItem) Descriptor() ([]byte, []int) {
	return file_api_group_v1_group_proto_rawDescGZIP(), []int{9}
}

func (x *PersonItem) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *PersonItem) GetStudentName() string {
	if x != nil {
		return x.StudentName
	}
	return ""
}

// 班级群组成员
type ClassItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassId       string                 `protobuf:"bytes,1,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	ClassName     string                 `protobuf:"bytes,2,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassItem) Reset() {
	*x = ClassItem{}
	mi := &file_api_group_v1_group_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassItem) ProtoMessage() {}

func (x *ClassItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_group_v1_group_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassItem.ProtoReflect.Descriptor instead.
func (*ClassItem) Descriptor() ([]byte, []int) {
	return file_api_group_v1_group_proto_rawDescGZIP(), []int{10}
}

func (x *ClassItem) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

func (x *ClassItem) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

// 群组详情
type GroupDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupInfo     *GroupInfo             `protobuf:"bytes,1,opt,name=group_info,json=groupInfo,proto3" json:"group_info,omitempty"`
	GradeLevel    []*GradeLevel          `protobuf:"bytes,2,rep,name=grade_level,json=gradeLevel,proto3" json:"grade_level,omitempty"`
	ClassInfoList []*ClassFullInfo       `protobuf:"bytes,3,rep,name=class_info_list,json=classInfoList,proto3" json:"class_info_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupDetail) Reset() {
	*x = GroupDetail{}
	mi := &file_api_group_v1_group_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupDetail) ProtoMessage() {}

func (x *GroupDetail) ProtoReflect() protoreflect.Message {
	mi := &file_api_group_v1_group_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupDetail.ProtoReflect.Descriptor instead.
func (*GroupDetail) Descriptor() ([]byte, []int) {
	return file_api_group_v1_group_proto_rawDescGZIP(), []int{11}
}

func (x *GroupDetail) GetGroupInfo() *GroupInfo {
	if x != nil {
		return x.GroupInfo
	}
	return nil
}

func (x *GroupDetail) GetGradeLevel() []*GradeLevel {
	if x != nil {
		return x.GradeLevel
	}
	return nil
}

func (x *GroupDetail) GetClassInfoList() []*ClassFullInfo {
	if x != nil {
		return x.ClassInfoList
	}
	return nil
}

// 群组项（用于班级群组列表）
type GroupItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	ClassList     []*ClassItem           `protobuf:"bytes,3,rep,name=class_list,json=classList,proto3" json:"class_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupItem) Reset() {
	*x = GroupItem{}
	mi := &file_api_group_v1_group_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupItem) ProtoMessage() {}

func (x *GroupItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_group_v1_group_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupItem.ProtoReflect.Descriptor instead.
func (*GroupItem) Descriptor() ([]byte, []int) {
	return file_api_group_v1_group_proto_rawDescGZIP(), []int{12}
}

func (x *GroupItem) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupItem) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *GroupItem) GetClassList() []*ClassItem {
	if x != nil {
		return x.ClassList
	}
	return nil
}

// 学生群组项（用于个人/职位群组列表）
type StudentGroupItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	PersonList    []*PersonItem          `protobuf:"bytes,3,rep,name=person_list,json=personList,proto3" json:"person_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentGroupItem) Reset() {
	*x = StudentGroupItem{}
	mi := &file_api_group_v1_group_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentGroupItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentGroupItem) ProtoMessage() {}

func (x *StudentGroupItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_group_v1_group_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentGroupItem.ProtoReflect.Descriptor instead.
func (*StudentGroupItem) Descriptor() ([]byte, []int) {
	return file_api_group_v1_group_proto_rawDescGZIP(), []int{13}
}

func (x *StudentGroupItem) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *StudentGroupItem) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *StudentGroupItem) GetPersonList() []*PersonItem {
	if x != nil {
		return x.PersonList
	}
	return nil
}

// 通用响应结构
type StandardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StandardResponse) Reset() {
	*x = StandardResponse{}
	mi := &file_api_group_v1_group_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StandardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StandardResponse) ProtoMessage() {}

func (x *StandardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_group_v1_group_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StandardResponse.ProtoReflect.Descriptor instead.
func (*StandardResponse) Descriptor() ([]byte, []int) {
	return file_api_group_v1_group_proto_rawDescGZIP(), []int{14}
}

func (x *StandardResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *StandardResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// --- 获取群组详情 ---
type GetGroupReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupReq) Reset() {
	*x = GetGroupReq{}
	mi := &file_api_group_v1_group_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupReq) ProtoMessage() {}

func (x *GetGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_group_v1_group_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupReq.ProtoReflect.Descriptor instead.
func (*GetGroupReq) Descriptor() ([]byte, []int) {
	return file_api_group_v1_group_proto_rawDescGZIP(), []int{15}
}

func (x *GetGroupReq) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type GetGroupResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *GroupDetail           `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupResp) Reset() {
	*x = GetGroupResp{}
	mi := &file_api_group_v1_group_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupResp) ProtoMessage() {}

func (x *GetGroupResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_group_v1_group_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupResp.ProtoReflect.Descriptor instead.
func (*GetGroupResp) Descriptor() ([]byte, []int) {
	return file_api_group_v1_group_proto_rawDescGZIP(), []int{16}
}

func (x *GetGroupResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetGroupResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetGroupResp) GetData() *GroupDetail {
	if x != nil {
		return x.Data
	}
	return nil
}

// --- 获取班级详情 ---
type GetClassDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassId       string                 `protobuf:"bytes,1,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClassDetailReq) Reset() {
	*x = GetClassDetailReq{}
	mi := &file_api_group_v1_group_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClassDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClassDetailReq) ProtoMessage() {}

func (x *GetClassDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_group_v1_group_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClassDetailReq.ProtoReflect.Descriptor instead.
func (*GetClassDetailReq) Descriptor() ([]byte, []int) {
	return file_api_group_v1_group_proto_rawDescGZIP(), []int{17}
}

func (x *GetClassDetailReq) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

type GetClassDetailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *ClassFullInfo         `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClassDetailResp) Reset() {
	*x = GetClassDetailResp{}
	mi := &file_api_group_v1_group_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClassDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClassDetailResp) ProtoMessage() {}

func (x *GetClassDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_group_v1_group_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClassDetailResp.ProtoReflect.Descriptor instead.
func (*GetClassDetailResp) Descriptor() ([]byte, []int) {
	return file_api_group_v1_group_proto_rawDescGZIP(), []int{18}
}

func (x *GetClassDetailResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetClassDetailResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetClassDetailResp) GetData() *ClassFullInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

// --- 搜索学生 ---
type SearchStudentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentName   string                 `protobuf:"bytes,1,opt,name=student_name,json=studentName,proto3" json:"student_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchStudentReq) Reset() {
	*x = SearchStudentReq{}
	mi := &file_api_group_v1_group_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchStudentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchStudentReq) ProtoMessage() {}

func (x *SearchStudentReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_group_v1_group_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchStudentReq.ProtoReflect.Descriptor instead.
func (*SearchStudentReq) Descriptor() ([]byte, []int) {
	return file_api_group_v1_group_proto_rawDescGZIP(), []int{19}
}

func (x *SearchStudentReq) GetStudentName() string {
	if x != nil {
		return x.StudentName
	}
	return ""
}

type SearchStudentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*StudentDetail       `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchStudentResp) Reset() {
	*x = SearchStudentResp{}
	mi := &file_api_group_v1_group_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchStudentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchStudentResp) ProtoMessage() {}

func (x *SearchStudentResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_group_v1_group_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchStudentResp.ProtoReflect.Descriptor instead.
func (*SearchStudentResp) Descriptor() ([]byte, []int) {
	return file_api_group_v1_group_proto_rawDescGZIP(), []int{20}
}

func (x *SearchStudentResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SearchStudentResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SearchStudentResp) GetData() []*StudentDetail {
	if x != nil {
		return x.Data
	}
	return nil
}

// --- 获取年级-班级结构树 ---
type GetGradeClassTreeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGradeClassTreeReq) Reset() {
	*x = GetGradeClassTreeReq{}
	mi := &file_api_group_v1_group_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGradeClassTreeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGradeClassTreeReq) ProtoMessage() {}

func (x *GetGradeClassTreeReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_group_v1_group_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGradeClassTreeReq.ProtoReflect.Descriptor instead.
func (*GetGradeClassTreeReq) Descriptor() ([]byte, []int) {
	return file_api_group_v1_group_proto_rawDescGZIP(), []int{21}
}

type GetGradeClassTreeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          []*GradeLevel          `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGradeClassTreeResp) Reset() {
	*x = GetGradeClassTreeResp{}
	mi := &file_api_group_v1_group_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGradeClassTreeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGradeClassTreeResp) ProtoMessage() {}

func (x *GetGradeClassTreeResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_group_v1_group_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGradeClassTreeResp.ProtoReflect.Descriptor instead.
func (*GetGradeClassTreeResp) Descriptor() ([]byte, []int) {
	return file_api_group_v1_group_proto_rawDescGZIP(), []int{22}
}

func (x *GetGradeClassTreeResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetGradeClassTreeResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetGradeClassTreeResp) GetData() []*GradeLevel {
	if x != nil {
		return x.Data
	}
	return nil
}

// --- 获取个人群组列表 ---
type GetPersonalGroupsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPersonalGroupsReq) Reset() {
	*x = GetPersonalGroupsReq{}
	mi := &file_api_group_v1_group_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPersonalGroupsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPersonalGroupsReq) ProtoMessage() {}

func (x *GetPersonalGroupsReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_group_v1_group_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPersonalGroupsReq.ProtoReflect.Descriptor instead.
func (*GetPersonalGroupsReq) Descriptor() ([]byte, []int) {
	return file_api_group_v1_group_proto_rawDescGZIP(), []int{23}
}

type ListPersonGroupResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*StudentGroupItem    `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPersonGroupResp) Reset() {
	*x = ListPersonGroupResp{}
	mi := &file_api_group_v1_group_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPersonGroupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPersonGroupResp) ProtoMessage() {}

func (x *ListPersonGroupResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_group_v1_group_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPersonGroupResp.ProtoReflect.Descriptor instead.
func (*ListPersonGroupResp) Descriptor() ([]byte, []int) {
	return file_api_group_v1_group_proto_rawDescGZIP(), []int{24}
}

func (x *ListPersonGroupResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListPersonGroupResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListPersonGroupResp) GetData() []*StudentGroupItem {
	if x != nil {
		return x.Data
	}
	return nil
}

// --- 获取职位群组列表 ---
type GetPositionGroupsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPositionGroupsReq) Reset() {
	*x = GetPositionGroupsReq{}
	mi := &file_api_group_v1_group_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPositionGroupsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionGroupsReq) ProtoMessage() {}

func (x *GetPositionGroupsReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_group_v1_group_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionGroupsReq.ProtoReflect.Descriptor instead.
func (*GetPositionGroupsReq) Descriptor() ([]byte, []int) {
	return file_api_group_v1_group_proto_rawDescGZIP(), []int{25}
}

type ListPositionGroupResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*StudentGroupItem    `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPositionGroupResp) Reset() {
	*x = ListPositionGroupResp{}
	mi := &file_api_group_v1_group_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPositionGroupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPositionGroupResp) ProtoMessage() {}

func (x *ListPositionGroupResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_group_v1_group_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPositionGroupResp.ProtoReflect.Descriptor instead.
func (*ListPositionGroupResp) Descriptor() ([]byte, []int) {
	return file_api_group_v1_group_proto_rawDescGZIP(), []int{26}
}

func (x *ListPositionGroupResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListPositionGroupResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListPositionGroupResp) GetData() []*StudentGroupItem {
	if x != nil {
		return x.Data
	}
	return nil
}

// --- 获取班级群组列表 ---
type GetClassGroupsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClassGroupsReq) Reset() {
	*x = GetClassGroupsReq{}
	mi := &file_api_group_v1_group_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClassGroupsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClassGroupsReq) ProtoMessage() {}

func (x *GetClassGroupsReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_group_v1_group_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClassGroupsReq.ProtoReflect.Descriptor instead.
func (*GetClassGroupsReq) Descriptor() ([]byte, []int) {
	return file_api_group_v1_group_proto_rawDescGZIP(), []int{27}
}

type ListClassGroupResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*GroupItem           `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClassGroupResp) Reset() {
	*x = ListClassGroupResp{}
	mi := &file_api_group_v1_group_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClassGroupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClassGroupResp) ProtoMessage() {}

func (x *ListClassGroupResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_group_v1_group_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClassGroupResp.ProtoReflect.Descriptor instead.
func (*ListClassGroupResp) Descriptor() ([]byte, []int) {
	return file_api_group_v1_group_proto_rawDescGZIP(), []int{28}
}

func (x *ListClassGroupResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListClassGroupResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListClassGroupResp) GetData() []*GroupItem {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteGroupReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupReq) Reset() {
	*x = DeleteGroupReq{}
	mi := &file_api_group_v1_group_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupReq) ProtoMessage() {}

func (x *DeleteGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_group_v1_group_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupReq.ProtoReflect.Descriptor instead.
func (*DeleteGroupReq) Descriptor() ([]byte, []int) {
	return file_api_group_v1_group_proto_rawDescGZIP(), []int{29}
}

func (x *DeleteGroupReq) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type CreateGroupReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	GroupName      string                 `protobuf:"bytes,1,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	Category       int32                  `protobuf:"varint,2,opt,name=category,proto3" json:"category,omitempty"`                                    // "0" 班级 / "1" 职位 / "2" 个人
	GradeLevelList []*GradeLevel          `protobuf:"bytes,3,rep,name=grade_level_list,json=gradeLevelList,proto3" json:"grade_level_list,omitempty"` // 年级层次结构
	Classes        []*ClassFullInfo       `protobuf:"bytes,4,rep,name=classes,proto3" json:"classes,omitempty"`                                       // 班级详细信息
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateGroupReq) Reset() {
	*x = CreateGroupReq{}
	mi := &file_api_group_v1_group_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupReq) ProtoMessage() {}

func (x *CreateGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_group_v1_group_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupReq.ProtoReflect.Descriptor instead.
func (*CreateGroupReq) Descriptor() ([]byte, []int) {
	return file_api_group_v1_group_proto_rawDescGZIP(), []int{30}
}

func (x *CreateGroupReq) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *CreateGroupReq) GetCategory() int32 {
	if x != nil {
		return x.Category
	}
	return 0
}

func (x *CreateGroupReq) GetGradeLevelList() []*GradeLevel {
	if x != nil {
		return x.GradeLevelList
	}
	return nil
}

func (x *CreateGroupReq) GetClasses() []*ClassFullInfo {
	if x != nil {
		return x.Classes
	}
	return nil
}

type UpdateGroupReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	GroupId        int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`                       // 群组ID
	GroupName      string                 `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`                  // 群组名称
	Category       int32                  `protobuf:"varint,3,opt,name=category,proto3" json:"category,omitempty"`                                    // 群组分类：0=班级，1=职位，2=按个人
	GradeLevelList []*GradeLevel          `protobuf:"bytes,4,rep,name=grade_level_list,json=gradeLevelList,proto3" json:"grade_level_list,omitempty"` // 年级层次结构（用于组织结构展示）
	Classes        []*ClassFullInfo       `protobuf:"bytes,5,rep,name=classes,proto3" json:"classes,omitempty"`                                       // 班级完整信息（用于精确展示勾选学生）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateGroupReq) Reset() {
	*x = UpdateGroupReq{}
	mi := &file_api_group_v1_group_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupReq) ProtoMessage() {}

func (x *UpdateGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_group_v1_group_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupReq.ProtoReflect.Descriptor instead.
func (*UpdateGroupReq) Descriptor() ([]byte, []int) {
	return file_api_group_v1_group_proto_rawDescGZIP(), []int{31}
}

func (x *UpdateGroupReq) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *UpdateGroupReq) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *UpdateGroupReq) GetCategory() int32 {
	if x != nil {
		return x.Category
	}
	return 0
}

func (x *UpdateGroupReq) GetGradeLevelList() []*GradeLevel {
	if x != nil {
		return x.GradeLevelList
	}
	return nil
}

func (x *UpdateGroupReq) GetClasses() []*ClassFullInfo {
	if x != nil {
		return x.Classes
	}
	return nil
}

var File_api_group_v1_group_proto protoreflect.FileDescriptor

const file_api_group_v1_group_proto_rawDesc = "" +
	"\n" +
	"\x18api/group/v1/group.proto\x12\n" +
	"GroupCheck\x1a\x1cgoogle/api/annotations.proto\":\n" +
	"\n" +
	"CommonResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"[\n" +
	"\tClassInfo\x12\x19\n" +
	"\bclass_id\x18\x01 \x01(\tR\aclassId\x12\x1d\n" +
	"\n" +
	"class_name\x18\x02 \x01(\tR\tclassName\x12\x14\n" +
	"\x05check\x18\x03 \x01(\bR\x05check\"e\n" +
	"\vStudentInfo\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12!\n" +
	"\fstudent_name\x18\x02 \x01(\tR\vstudentName\x12\x14\n" +
	"\x05check\x18\x03 \x01(\bR\x05check\"r\n" +
	"\n" +
	"GradeLevel\x12\x19\n" +
	"\bgrade_id\x18\x01 \x01(\tR\agradeId\x12\x14\n" +
	"\x05check\x18\x02 \x01(\bR\x05check\x123\n" +
	"\bsubjects\x18\x03 \x03(\v2\x17.GroupCheck.SubjectInfoR\bsubjects\"w\n" +
	"\vSubjectInfo\x12!\n" +
	"\fsubject_name\x18\x01 \x01(\tR\vsubjectName\x12\x14\n" +
	"\x05check\x18\x02 \x01(\bR\x05check\x12/\n" +
	"\aclasses\x18\x03 \x03(\v2\x15.GroupCheck.ClassInfoR\aclasses\"\xbc\x01\n" +
	"\rClassFullInfo\x12\x19\n" +
	"\bgrade_id\x18\x01 \x01(\tR\agradeId\x12!\n" +
	"\fsubject_name\x18\x02 \x01(\tR\vsubjectName\x12\x19\n" +
	"\bclass_id\x18\x03 \x01(\tR\aclassId\x12\x1d\n" +
	"\n" +
	"class_name\x18\x04 \x01(\tR\tclassName\x123\n" +
	"\bstudents\x18\x05 \x03(\v2\x17.GroupCheck.StudentInfoR\bstudents\"`\n" +
	"\x0eClassBasicInfo\x12\x19\n" +
	"\bclass_id\x18\x01 \x01(\tR\aclassId\x12\x1d\n" +
	"\n" +
	"class_name\x18\x02 \x01(\tR\tclassName\x12\x14\n" +
	"\x05check\x18\x03 \x01(\bR\x05check\"\xaa\x01\n" +
	"\rStudentDetail\x12\x19\n" +
	"\bgrade_id\x18\x01 \x01(\tR\agradeId\x12!\n" +
	"\fsubject_name\x18\x02 \x01(\tR\vsubjectName\x12\x19\n" +
	"\bclass_id\x18\x03 \x01(\tR\aclassId\x12!\n" +
	"\fstudent_name\x18\x04 \x01(\tR\vstudentName\x12\x1d\n" +
	"\n" +
	"student_id\x18\x05 \x01(\tR\tstudentId\"a\n" +
	"\tGroupInfo\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x05R\agroupId\x12\x1d\n" +
	"\n" +
	"group_name\x18\x02 \x01(\tR\tgroupName\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\x05R\bcategory\"N\n" +
	"\n" +
	"PersonItem\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12!\n" +
	"\fstudent_name\x18\x02 \x01(\tR\vstudentName\"E\n" +
	"\tClassItem\x12\x19\n" +
	"\bclass_id\x18\x01 \x01(\tR\aclassId\x12\x1d\n" +
	"\n" +
	"class_name\x18\x02 \x01(\tR\tclassName\"\xbf\x01\n" +
	"\vGroupDetail\x124\n" +
	"\n" +
	"group_info\x18\x01 \x01(\v2\x15.GroupCheck.GroupInfoR\tgroupInfo\x127\n" +
	"\vgrade_level\x18\x02 \x03(\v2\x16.GroupCheck.GradeLevelR\n" +
	"gradeLevel\x12A\n" +
	"\x0fclass_info_list\x18\x03 \x03(\v2\x19.GroupCheck.ClassFullInfoR\rclassInfoList\"{\n" +
	"\tGroupItem\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x05R\agroupId\x12\x1d\n" +
	"\n" +
	"group_name\x18\x02 \x01(\tR\tgroupName\x124\n" +
	"\n" +
	"class_list\x18\x03 \x03(\v2\x15.GroupCheck.ClassItemR\tclassList\"\x85\x01\n" +
	"\x10StudentGroupItem\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x05R\agroupId\x12\x1d\n" +
	"\n" +
	"group_name\x18\x02 \x01(\tR\tgroupName\x127\n" +
	"\vperson_list\x18\x03 \x03(\v2\x16.GroupCheck.PersonItemR\n" +
	"personList\"@\n" +
	"\x10StandardResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"(\n" +
	"\vGetGroupReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x05R\agroupId\"i\n" +
	"\fGetGroupResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.GroupCheck.GroupDetailR\x04data\".\n" +
	"\x11GetClassDetailReq\x12\x19\n" +
	"\bclass_id\x18\x01 \x01(\tR\aclassId\"i\n" +
	"\x12GetClassDetailResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12-\n" +
	"\x04data\x18\x03 \x01(\v2\x19.GroupCheck.ClassFullInfoR\x04data\"5\n" +
	"\x10SearchStudentReq\x12!\n" +
	"\fstudent_name\x18\x01 \x01(\tR\vstudentName\"p\n" +
	"\x11SearchStudentResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\x04data\x18\x03 \x03(\v2\x19.GroupCheck.StudentDetailR\x04data\"\x16\n" +
	"\x14GetGradeClassTreeReq\"i\n" +
	"\x15GetGradeClassTreeResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12*\n" +
	"\x04data\x18\x03 \x03(\v2\x16.GroupCheck.GradeLevelR\x04data\"\x16\n" +
	"\x14GetPersonalGroupsReq\"u\n" +
	"\x13ListPersonGroupResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\x04data\x18\x03 \x03(\v2\x1c.GroupCheck.StudentGroupItemR\x04data\"\x16\n" +
	"\x14GetPositionGroupsReq\"w\n" +
	"\x15ListPositionGroupResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\x04data\x18\x03 \x03(\v2\x1c.GroupCheck.StudentGroupItemR\x04data\"\x13\n" +
	"\x11GetClassGroupsReq\"m\n" +
	"\x12ListClassGroupResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x04data\x18\x03 \x03(\v2\x15.GroupCheck.GroupItemR\x04data\"+\n" +
	"\x0eDeleteGroupReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x05R\agroupId\"\xc2\x01\n" +
	"\x0eCreateGroupReq\x12\x1d\n" +
	"\n" +
	"group_name\x18\x01 \x01(\tR\tgroupName\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\x05R\bcategory\x12@\n" +
	"\x10grade_level_list\x18\x03 \x03(\v2\x16.GroupCheck.GradeLevelR\x0egradeLevelList\x123\n" +
	"\aclasses\x18\x04 \x03(\v2\x19.GroupCheck.ClassFullInfoR\aclasses\"\xdd\x01\n" +
	"\x0eUpdateGroupReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x05R\agroupId\x12\x1d\n" +
	"\n" +
	"group_name\x18\x02 \x01(\tR\tgroupName\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\x05R\bcategory\x12@\n" +
	"\x10grade_level_list\x18\x04 \x03(\v2\x16.GroupCheck.GradeLevelR\x0egradeLevelList\x123\n" +
	"\aclasses\x18\x05 \x03(\v2\x19.GroupCheck.ClassFullInfoR\aclasses2\xde\b\n" +
	"\x05Group\x12`\n" +
	"\x0eGetGroupDetail\x12\x17.GroupCheck.GetGroupReq\x1a\x18.GroupCheck.GetGroupResp\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/group/check/detail\x12s\n" +
	"\x0eGetClassDetail\x12\x1d.GroupCheck.GetClassDetailReq\x1a\x1e.GroupCheck.GetClassDetailResp\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/group/check/class/details\x12k\n" +
	"\rSearchStudent\x12\x1c.GroupCheck.SearchStudentReq\x1a\x1d.GroupCheck.SearchStudentResp\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/group/check/students\x12~\n" +
	"\x11GetGradeClassTree\x12 .GroupCheck.GetGradeClassTreeReq\x1a!.GroupCheck.GetGradeClassTreeResp\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/group/check/grade-structure\x12x\n" +
	"\x0fListPersonGroup\x12 .GroupCheck.GetPersonalGroupsReq\x1a\x1f.GroupCheck.ListPersonGroupResp\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/group/check/list/personal\x12|\n" +
	"\x11ListPositionGroup\x12 .GroupCheck.GetPositionGroupsReq\x1a!.GroupCheck.ListPositionGroupResp\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/group/check/list/position\x12p\n" +
	"\x0eListClassGroup\x12\x1d.GroupCheck.GetClassGroupsReq\x1a\x1e.GroupCheck.ListClassGroupResp\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/group/check/list/class\x12b\n" +
	"\vDeleteGroup\x12\x1a.GroupCheck.DeleteGroupReq\x1a\x16.GroupCheck.CommonResp\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/group/manage/delete\x12_\n" +
	"\vCreateGroup\x12\x1a.GroupCheck.CreateGroupReq\x1a\x16.GroupCheck.CommonResp\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/group/manage/add\x12b\n" +
	"\vUpdateGroup\x12\x1a.GroupCheck.UpdateGroupReq\x1a\x16.GroupCheck.CommonResp\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/group/manage/updateB6Z4ArgoNavisV1/GroupCheck/api/groupCheck/v1;group_checkb\x06proto3"

var (
	file_api_group_v1_group_proto_rawDescOnce sync.Once
	file_api_group_v1_group_proto_rawDescData []byte
)

func file_api_group_v1_group_proto_rawDescGZIP() []byte {
	file_api_group_v1_group_proto_rawDescOnce.Do(func() {
		file_api_group_v1_group_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_group_v1_group_proto_rawDesc), len(file_api_group_v1_group_proto_rawDesc)))
	})
	return file_api_group_v1_group_proto_rawDescData
}

var file_api_group_v1_group_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_api_group_v1_group_proto_goTypes = []any{
	(*CommonResp)(nil),            // 0: GroupCheck.CommonResp
	(*ClassInfo)(nil),             // 1: GroupCheck.ClassInfo
	(*StudentInfo)(nil),           // 2: GroupCheck.StudentInfo
	(*GradeLevel)(nil),            // 3: GroupCheck.GradeLevel
	(*SubjectInfo)(nil),           // 4: GroupCheck.SubjectInfo
	(*ClassFullInfo)(nil),         // 5: GroupCheck.ClassFullInfo
	(*ClassBasicInfo)(nil),        // 6: GroupCheck.ClassBasicInfo
	(*StudentDetail)(nil),         // 7: GroupCheck.StudentDetail
	(*GroupInfo)(nil),             // 8: GroupCheck.GroupInfo
	(*PersonItem)(nil),            // 9: GroupCheck.PersonItem
	(*ClassItem)(nil),             // 10: GroupCheck.ClassItem
	(*GroupDetail)(nil),           // 11: GroupCheck.GroupDetail
	(*GroupItem)(nil),             // 12: GroupCheck.GroupItem
	(*StudentGroupItem)(nil),      // 13: GroupCheck.StudentGroupItem
	(*StandardResponse)(nil),      // 14: GroupCheck.StandardResponse
	(*GetGroupReq)(nil),           // 15: GroupCheck.GetGroupReq
	(*GetGroupResp)(nil),          // 16: GroupCheck.GetGroupResp
	(*GetClassDetailReq)(nil),     // 17: GroupCheck.GetClassDetailReq
	(*GetClassDetailResp)(nil),    // 18: GroupCheck.GetClassDetailResp
	(*SearchStudentReq)(nil),      // 19: GroupCheck.SearchStudentReq
	(*SearchStudentResp)(nil),     // 20: GroupCheck.SearchStudentResp
	(*GetGradeClassTreeReq)(nil),  // 21: GroupCheck.GetGradeClassTreeReq
	(*GetGradeClassTreeResp)(nil), // 22: GroupCheck.GetGradeClassTreeResp
	(*GetPersonalGroupsReq)(nil),  // 23: GroupCheck.GetPersonalGroupsReq
	(*ListPersonGroupResp)(nil),   // 24: GroupCheck.ListPersonGroupResp
	(*GetPositionGroupsReq)(nil),  // 25: GroupCheck.GetPositionGroupsReq
	(*ListPositionGroupResp)(nil), // 26: GroupCheck.ListPositionGroupResp
	(*GetClassGroupsReq)(nil),     // 27: GroupCheck.GetClassGroupsReq
	(*ListClassGroupResp)(nil),    // 28: GroupCheck.ListClassGroupResp
	(*DeleteGroupReq)(nil),        // 29: GroupCheck.DeleteGroupReq
	(*CreateGroupReq)(nil),        // 30: GroupCheck.CreateGroupReq
	(*UpdateGroupReq)(nil),        // 31: GroupCheck.UpdateGroupReq
}
var file_api_group_v1_group_proto_depIdxs = []int32{
	4,  // 0: GroupCheck.GradeLevel.subjects:type_name -> GroupCheck.SubjectInfo
	1,  // 1: GroupCheck.SubjectInfo.classes:type_name -> GroupCheck.ClassInfo
	2,  // 2: GroupCheck.ClassFullInfo.students:type_name -> GroupCheck.StudentInfo
	8,  // 3: GroupCheck.GroupDetail.group_info:type_name -> GroupCheck.GroupInfo
	3,  // 4: GroupCheck.GroupDetail.grade_level:type_name -> GroupCheck.GradeLevel
	5,  // 5: GroupCheck.GroupDetail.class_info_list:type_name -> GroupCheck.ClassFullInfo
	10, // 6: GroupCheck.GroupItem.class_list:type_name -> GroupCheck.ClassItem
	9,  // 7: GroupCheck.StudentGroupItem.person_list:type_name -> GroupCheck.PersonItem
	11, // 8: GroupCheck.GetGroupResp.data:type_name -> GroupCheck.GroupDetail
	5,  // 9: GroupCheck.GetClassDetailResp.data:type_name -> GroupCheck.ClassFullInfo
	7,  // 10: GroupCheck.SearchStudentResp.data:type_name -> GroupCheck.StudentDetail
	3,  // 11: GroupCheck.GetGradeClassTreeResp.data:type_name -> GroupCheck.GradeLevel
	13, // 12: GroupCheck.ListPersonGroupResp.data:type_name -> GroupCheck.StudentGroupItem
	13, // 13: GroupCheck.ListPositionGroupResp.data:type_name -> GroupCheck.StudentGroupItem
	12, // 14: GroupCheck.ListClassGroupResp.data:type_name -> GroupCheck.GroupItem
	3,  // 15: GroupCheck.CreateGroupReq.grade_level_list:type_name -> GroupCheck.GradeLevel
	5,  // 16: GroupCheck.CreateGroupReq.classes:type_name -> GroupCheck.ClassFullInfo
	3,  // 17: GroupCheck.UpdateGroupReq.grade_level_list:type_name -> GroupCheck.GradeLevel
	5,  // 18: GroupCheck.UpdateGroupReq.classes:type_name -> GroupCheck.ClassFullInfo
	15, // 19: GroupCheck.Group.GetGroupDetail:input_type -> GroupCheck.GetGroupReq
	17, // 20: GroupCheck.Group.GetClassDetail:input_type -> GroupCheck.GetClassDetailReq
	19, // 21: GroupCheck.Group.SearchStudent:input_type -> GroupCheck.SearchStudentReq
	21, // 22: GroupCheck.Group.GetGradeClassTree:input_type -> GroupCheck.GetGradeClassTreeReq
	23, // 23: GroupCheck.Group.ListPersonGroup:input_type -> GroupCheck.GetPersonalGroupsReq
	25, // 24: GroupCheck.Group.ListPositionGroup:input_type -> GroupCheck.GetPositionGroupsReq
	27, // 25: GroupCheck.Group.ListClassGroup:input_type -> GroupCheck.GetClassGroupsReq
	29, // 26: GroupCheck.Group.DeleteGroup:input_type -> GroupCheck.DeleteGroupReq
	30, // 27: GroupCheck.Group.CreateGroup:input_type -> GroupCheck.CreateGroupReq
	31, // 28: GroupCheck.Group.UpdateGroup:input_type -> GroupCheck.UpdateGroupReq
	16, // 29: GroupCheck.Group.GetGroupDetail:output_type -> GroupCheck.GetGroupResp
	18, // 30: GroupCheck.Group.GetClassDetail:output_type -> GroupCheck.GetClassDetailResp
	20, // 31: GroupCheck.Group.SearchStudent:output_type -> GroupCheck.SearchStudentResp
	22, // 32: GroupCheck.Group.GetGradeClassTree:output_type -> GroupCheck.GetGradeClassTreeResp
	24, // 33: GroupCheck.Group.ListPersonGroup:output_type -> GroupCheck.ListPersonGroupResp
	26, // 34: GroupCheck.Group.ListPositionGroup:output_type -> GroupCheck.ListPositionGroupResp
	28, // 35: GroupCheck.Group.ListClassGroup:output_type -> GroupCheck.ListClassGroupResp
	0,  // 36: GroupCheck.Group.DeleteGroup:output_type -> GroupCheck.CommonResp
	0,  // 37: GroupCheck.Group.CreateGroup:output_type -> GroupCheck.CommonResp
	0,  // 38: GroupCheck.Group.UpdateGroup:output_type -> GroupCheck.CommonResp
	29, // [29:39] is the sub-list for method output_type
	19, // [19:29] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_api_group_v1_group_proto_init() }
func file_api_group_v1_group_proto_init() {
	if File_api_group_v1_group_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_group_v1_group_proto_rawDesc), len(file_api_group_v1_group_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_group_v1_group_proto_goTypes,
		DependencyIndexes: file_api_group_v1_group_proto_depIdxs,
		MessageInfos:      file_api_group_v1_group_proto_msgTypes,
	}.Build()
	File_api_group_v1_group_proto = out.File
	file_api_group_v1_group_proto_goTypes = nil
	file_api_group_v1_group_proto_depIdxs = nil
}
