// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: api/groupCheck/v1/group_check.proto

package group_check

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 学生信息
type StudentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	StudentName   string                 `protobuf:"bytes,2,opt,name=student_name,json=studentName,proto3" json:"student_name,omitempty"`
	Check         bool                   `protobuf:"varint,3,opt,name=check,proto3" json:"check,omitempty"` // 是否勾选
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentInfo) Reset() {
	*x = StudentInfo{}
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentInfo) ProtoMessage() {}

func (x *StudentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentInfo.ProtoReflect.Descriptor instead.
func (*StudentInfo) Descriptor() ([]byte, []int) {
	return file_api_groupCheck_v1_group_check_proto_rawDescGZIP(), []int{0}
}

func (x *StudentInfo) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *StudentInfo) GetStudentName() string {
	if x != nil {
		return x.StudentName
	}
	return ""
}

func (x *StudentInfo) GetCheck() bool {
	if x != nil {
		return x.Check
	}
	return false
}

// 班级基本信息
type ClassBasicInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassId       string                 `protobuf:"bytes,1,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	ClassName     string                 `protobuf:"bytes,2,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	Check         bool                   `protobuf:"varint,3,opt,name=check,proto3" json:"check,omitempty"` // 是否勾选
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassBasicInfo) Reset() {
	*x = ClassBasicInfo{}
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassBasicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassBasicInfo) ProtoMessage() {}

func (x *ClassBasicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassBasicInfo.ProtoReflect.Descriptor instead.
func (*ClassBasicInfo) Descriptor() ([]byte, []int) {
	return file_api_groupCheck_v1_group_check_proto_rawDescGZIP(), []int{1}
}

func (x *ClassBasicInfo) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

func (x *ClassBasicInfo) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *ClassBasicInfo) GetCheck() bool {
	if x != nil {
		return x.Check
	}
	return false
}

// 专业信息
type SubjectInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubjectName   string                 `protobuf:"bytes,1,opt,name=subject_name,json=subjectName,proto3" json:"subject_name,omitempty"`
	Check         bool                   `protobuf:"varint,2,opt,name=check,proto3" json:"check,omitempty"`    // 是否勾选
	Classes       []*ClassBasicInfo      `protobuf:"bytes,3,rep,name=classes,proto3" json:"classes,omitempty"` // 班级列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubjectInfo) Reset() {
	*x = SubjectInfo{}
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectInfo) ProtoMessage() {}

func (x *SubjectInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectInfo.ProtoReflect.Descriptor instead.
func (*SubjectInfo) Descriptor() ([]byte, []int) {
	return file_api_groupCheck_v1_group_check_proto_rawDescGZIP(), []int{2}
}

func (x *SubjectInfo) GetSubjectName() string {
	if x != nil {
		return x.SubjectName
	}
	return ""
}

func (x *SubjectInfo) GetCheck() bool {
	if x != nil {
		return x.Check
	}
	return false
}

func (x *SubjectInfo) GetClasses() []*ClassBasicInfo {
	if x != nil {
		return x.Classes
	}
	return nil
}

// 年级信息
type GradeLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GradeId       string                 `protobuf:"bytes,1,opt,name=grade_id,json=gradeId,proto3" json:"grade_id,omitempty"`
	Check         bool                   `protobuf:"varint,2,opt,name=check,proto3" json:"check,omitempty"`      // 是否勾选
	Subjects      []*SubjectInfo         `protobuf:"bytes,3,rep,name=subjects,proto3" json:"subjects,omitempty"` // 专业列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradeLevel) Reset() {
	*x = GradeLevel{}
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeLevel) ProtoMessage() {}

func (x *GradeLevel) ProtoReflect() protoreflect.Message {
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeLevel.ProtoReflect.Descriptor instead.
func (*GradeLevel) Descriptor() ([]byte, []int) {
	return file_api_groupCheck_v1_group_check_proto_rawDescGZIP(), []int{3}
}

func (x *GradeLevel) GetGradeId() string {
	if x != nil {
		return x.GradeId
	}
	return ""
}

func (x *GradeLevel) GetCheck() bool {
	if x != nil {
		return x.Check
	}
	return false
}

func (x *GradeLevel) GetSubjects() []*SubjectInfo {
	if x != nil {
		return x.Subjects
	}
	return nil
}

// 班级完整信息
type ClassFullInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GradeId       string                 `protobuf:"bytes,1,opt,name=grade_id,json=gradeId,proto3" json:"grade_id,omitempty"`
	SubjectName   string                 `protobuf:"bytes,2,opt,name=subject_name,json=subjectName,proto3" json:"subject_name,omitempty"`
	ClassId       string                 `protobuf:"bytes,3,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	ClassName     string                 `protobuf:"bytes,4,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	Students      []*StudentInfo         `protobuf:"bytes,5,rep,name=students,proto3" json:"students,omitempty"` // 班级学生
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassFullInfo) Reset() {
	*x = ClassFullInfo{}
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassFullInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassFullInfo) ProtoMessage() {}

func (x *ClassFullInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassFullInfo.ProtoReflect.Descriptor instead.
func (*ClassFullInfo) Descriptor() ([]byte, []int) {
	return file_api_groupCheck_v1_group_check_proto_rawDescGZIP(), []int{4}
}

func (x *ClassFullInfo) GetGradeId() string {
	if x != nil {
		return x.GradeId
	}
	return ""
}

func (x *ClassFullInfo) GetSubjectName() string {
	if x != nil {
		return x.SubjectName
	}
	return ""
}

func (x *ClassFullInfo) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

func (x *ClassFullInfo) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *ClassFullInfo) GetStudents() []*StudentInfo {
	if x != nil {
		return x.Students
	}
	return nil
}

// 群组基本信息
type GroupInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	Category      int32                  `protobuf:"varint,3,opt,name=category,proto3" json:"category,omitempty"` // 0=班级，1=职位，2=按个人
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupInfo) Reset() {
	*x = GroupInfo{}
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInfo) ProtoMessage() {}

func (x *GroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupInfo.ProtoReflect.Descriptor instead.
func (*GroupInfo) Descriptor() ([]byte, []int) {
	return file_api_groupCheck_v1_group_check_proto_rawDescGZIP(), []int{5}
}

func (x *GroupInfo) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupInfo) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *GroupInfo) GetCategory() int32 {
	if x != nil {
		return x.Category
	}
	return 0
}

// 个人群组/职位群组成员
type PersonItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	StudentName   string                 `protobuf:"bytes,2,opt,name=student_name,json=studentName,proto3" json:"student_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonItem) Reset() {
	*x = PersonItem{}
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonItem) ProtoMessage() {}

func (x *PersonItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonItem.ProtoReflect.Descriptor instead.
func (*PersonItem) Descriptor() ([]byte, []int) {
	return file_api_groupCheck_v1_group_check_proto_rawDescGZIP(), []int{6}
}

func (x *PersonItem) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *PersonItem) GetStudentName() string {
	if x != nil {
		return x.StudentName
	}
	return ""
}

// 班级群组成员
type ClassItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassId       string                 `protobuf:"bytes,1,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	ClassName     string                 `protobuf:"bytes,2,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassItem) Reset() {
	*x = ClassItem{}
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassItem) ProtoMessage() {}

func (x *ClassItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassItem.ProtoReflect.Descriptor instead.
func (*ClassItem) Descriptor() ([]byte, []int) {
	return file_api_groupCheck_v1_group_check_proto_rawDescGZIP(), []int{7}
}

func (x *ClassItem) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

func (x *ClassItem) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

// 学生详情
type StudentDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GradeId       string                 `protobuf:"bytes,1,opt,name=grade_id,json=gradeId,proto3" json:"grade_id,omitempty"`
	SubjectName   string                 `protobuf:"bytes,2,opt,name=subject_name,json=subjectName,proto3" json:"subject_name,omitempty"`
	ClassId       string                 `protobuf:"bytes,3,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	StudentName   string                 `protobuf:"bytes,4,opt,name=student_name,json=studentName,proto3" json:"student_name,omitempty"`
	StudentId     string                 `protobuf:"bytes,5,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentDetail) Reset() {
	*x = StudentDetail{}
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentDetail) ProtoMessage() {}

func (x *StudentDetail) ProtoReflect() protoreflect.Message {
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentDetail.ProtoReflect.Descriptor instead.
func (*StudentDetail) Descriptor() ([]byte, []int) {
	return file_api_groupCheck_v1_group_check_proto_rawDescGZIP(), []int{8}
}

func (x *StudentDetail) GetGradeId() string {
	if x != nil {
		return x.GradeId
	}
	return ""
}

func (x *StudentDetail) GetSubjectName() string {
	if x != nil {
		return x.SubjectName
	}
	return ""
}

func (x *StudentDetail) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

func (x *StudentDetail) GetStudentName() string {
	if x != nil {
		return x.StudentName
	}
	return ""
}

func (x *StudentDetail) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

// 获取群组详情请求
type GetGroupReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupReq) Reset() {
	*x = GetGroupReq{}
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupReq) ProtoMessage() {}

func (x *GetGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupReq.ProtoReflect.Descriptor instead.
func (*GetGroupReq) Descriptor() ([]byte, []int) {
	return file_api_groupCheck_v1_group_check_proto_rawDescGZIP(), []int{9}
}

func (x *GetGroupReq) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

// 获取群组详情响应
type GetGroupResp struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Code          int32                     `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	GroupDetail   *GetGroupResp_GroupDetail `protobuf:"bytes,3,opt,name=group_detail,json=groupDetail,proto3" json:"group_detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupResp) Reset() {
	*x = GetGroupResp{}
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupResp) ProtoMessage() {}

func (x *GetGroupResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupResp.ProtoReflect.Descriptor instead.
func (*GetGroupResp) Descriptor() ([]byte, []int) {
	return file_api_groupCheck_v1_group_check_proto_rawDescGZIP(), []int{10}
}

func (x *GetGroupResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetGroupResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetGroupResp) GetGroupDetail() *GetGroupResp_GroupDetail {
	if x != nil {
		return x.GroupDetail
	}
	return nil
}

// 获取班级详情请求
type GetClassDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassId       string                 `protobuf:"bytes,1,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClassDetailReq) Reset() {
	*x = GetClassDetailReq{}
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClassDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClassDetailReq) ProtoMessage() {}

func (x *GetClassDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClassDetailReq.ProtoReflect.Descriptor instead.
func (*GetClassDetailReq) Descriptor() ([]byte, []int) {
	return file_api_groupCheck_v1_group_check_proto_rawDescGZIP(), []int{11}
}

func (x *GetClassDetailReq) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

// 获取班级详情响应
type GetClassDetailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	ClassInfo     *ClassFullInfo         `protobuf:"bytes,3,opt,name=class_info,json=classInfo,proto3" json:"class_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClassDetailResp) Reset() {
	*x = GetClassDetailResp{}
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClassDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClassDetailResp) ProtoMessage() {}

func (x *GetClassDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClassDetailResp.ProtoReflect.Descriptor instead.
func (*GetClassDetailResp) Descriptor() ([]byte, []int) {
	return file_api_groupCheck_v1_group_check_proto_rawDescGZIP(), []int{12}
}

func (x *GetClassDetailResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetClassDetailResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetClassDetailResp) GetClassInfo() *ClassFullInfo {
	if x != nil {
		return x.ClassInfo
	}
	return nil
}

// 搜索学生请求
type SearchStudentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentName   string                 `protobuf:"bytes,1,opt,name=student_name,json=studentName,proto3" json:"student_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchStudentReq) Reset() {
	*x = SearchStudentReq{}
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchStudentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchStudentReq) ProtoMessage() {}

func (x *SearchStudentReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchStudentReq.ProtoReflect.Descriptor instead.
func (*SearchStudentReq) Descriptor() ([]byte, []int) {
	return file_api_groupCheck_v1_group_check_proto_rawDescGZIP(), []int{13}
}

func (x *SearchStudentReq) GetStudentName() string {
	if x != nil {
		return x.StudentName
	}
	return ""
}

// 搜索学生响应
type SearchStudentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*StudentDetail       `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchStudentResp) Reset() {
	*x = SearchStudentResp{}
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchStudentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchStudentResp) ProtoMessage() {}

func (x *SearchStudentResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchStudentResp.ProtoReflect.Descriptor instead.
func (*SearchStudentResp) Descriptor() ([]byte, []int) {
	return file_api_groupCheck_v1_group_check_proto_rawDescGZIP(), []int{14}
}

func (x *SearchStudentResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SearchStudentResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SearchStudentResp) GetData() []*StudentDetail {
	if x != nil {
		return x.Data
	}
	return nil
}

// 获取班级树请求
type GetGradeClassTreeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGradeClassTreeReq) Reset() {
	*x = GetGradeClassTreeReq{}
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGradeClassTreeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGradeClassTreeReq) ProtoMessage() {}

func (x *GetGradeClassTreeReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGradeClassTreeReq.ProtoReflect.Descriptor instead.
func (*GetGradeClassTreeReq) Descriptor() ([]byte, []int) {
	return file_api_groupCheck_v1_group_check_proto_rawDescGZIP(), []int{15}
}

type GetPersonalGroupsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPersonalGroupsReq) Reset() {
	*x = GetPersonalGroupsReq{}
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPersonalGroupsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPersonalGroupsReq) ProtoMessage() {}

func (x *GetPersonalGroupsReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPersonalGroupsReq.ProtoReflect.Descriptor instead.
func (*GetPersonalGroupsReq) Descriptor() ([]byte, []int) {
	return file_api_groupCheck_v1_group_check_proto_rawDescGZIP(), []int{16}
}

type GetClassGroupsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClassGroupsReq) Reset() {
	*x = GetClassGroupsReq{}
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClassGroupsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClassGroupsReq) ProtoMessage() {}

func (x *GetClassGroupsReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClassGroupsReq.ProtoReflect.Descriptor instead.
func (*GetClassGroupsReq) Descriptor() ([]byte, []int) {
	return file_api_groupCheck_v1_group_check_proto_rawDescGZIP(), []int{17}
}

type GetPositionGroupsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPositionGroupsReq) Reset() {
	*x = GetPositionGroupsReq{}
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPositionGroupsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionGroupsReq) ProtoMessage() {}

func (x *GetPositionGroupsReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionGroupsReq.ProtoReflect.Descriptor instead.
func (*GetPositionGroupsReq) Descriptor() ([]byte, []int) {
	return file_api_groupCheck_v1_group_check_proto_rawDescGZIP(), []int{18}
}

// 获取班级树响应
type GetGradeClassTreeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          []*GradeLevel          `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGradeClassTreeResp) Reset() {
	*x = GetGradeClassTreeResp{}
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGradeClassTreeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGradeClassTreeResp) ProtoMessage() {}

func (x *GetGradeClassTreeResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGradeClassTreeResp.ProtoReflect.Descriptor instead.
func (*GetGradeClassTreeResp) Descriptor() ([]byte, []int) {
	return file_api_groupCheck_v1_group_check_proto_rawDescGZIP(), []int{19}
}

func (x *GetGradeClassTreeResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetGradeClassTreeResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetGradeClassTreeResp) GetData() []*GradeLevel {
	if x != nil {
		return x.Data
	}
	return nil
}

// 获取个人群组列表响应
type ListPersonGroupResp struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Code          int32                            `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data          []*ListPersonGroupResp_GroupItem `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPersonGroupResp) Reset() {
	*x = ListPersonGroupResp{}
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPersonGroupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPersonGroupResp) ProtoMessage() {}

func (x *ListPersonGroupResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPersonGroupResp.ProtoReflect.Descriptor instead.
func (*ListPersonGroupResp) Descriptor() ([]byte, []int) {
	return file_api_groupCheck_v1_group_check_proto_rawDescGZIP(), []int{20}
}

func (x *ListPersonGroupResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListPersonGroupResp) GetData() []*ListPersonGroupResp_GroupItem {
	if x != nil {
		return x.Data
	}
	return nil
}

// 获取职位群组列表响应
type ListPositionGroupResp struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Code          int32                              `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data          []*ListPositionGroupResp_GroupItem `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPositionGroupResp) Reset() {
	*x = ListPositionGroupResp{}
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPositionGroupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPositionGroupResp) ProtoMessage() {}

func (x *ListPositionGroupResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPositionGroupResp.ProtoReflect.Descriptor instead.
func (*ListPositionGroupResp) Descriptor() ([]byte, []int) {
	return file_api_groupCheck_v1_group_check_proto_rawDescGZIP(), []int{21}
}

func (x *ListPositionGroupResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListPositionGroupResp) GetData() []*ListPositionGroupResp_GroupItem {
	if x != nil {
		return x.Data
	}
	return nil
}

// 获取班级群组列表响应
type ListClassGroupResp struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Code          int32                           `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data          []*ListClassGroupResp_GroupItem `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClassGroupResp) Reset() {
	*x = ListClassGroupResp{}
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClassGroupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClassGroupResp) ProtoMessage() {}

func (x *ListClassGroupResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClassGroupResp.ProtoReflect.Descriptor instead.
func (*ListClassGroupResp) Descriptor() ([]byte, []int) {
	return file_api_groupCheck_v1_group_check_proto_rawDescGZIP(), []int{22}
}

func (x *ListClassGroupResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListClassGroupResp) GetData() []*ListClassGroupResp_GroupItem {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetGroupResp_GroupDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupInfo     *GroupInfo             `protobuf:"bytes,1,opt,name=group_info,json=groupInfo,proto3" json:"group_info,omitempty"`
	GradeLevel    []*GradeLevel          `protobuf:"bytes,2,rep,name=grade_level,json=gradeLevel,proto3" json:"grade_level,omitempty"`
	ClassInfoList []*ClassFullInfo       `protobuf:"bytes,3,rep,name=class_info_list,json=classInfoList,proto3" json:"class_info_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupResp_GroupDetail) Reset() {
	*x = GetGroupResp_GroupDetail{}
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupResp_GroupDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupResp_GroupDetail) ProtoMessage() {}

func (x *GetGroupResp_GroupDetail) ProtoReflect() protoreflect.Message {
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupResp_GroupDetail.ProtoReflect.Descriptor instead.
func (*GetGroupResp_GroupDetail) Descriptor() ([]byte, []int) {
	return file_api_groupCheck_v1_group_check_proto_rawDescGZIP(), []int{10, 0}
}

func (x *GetGroupResp_GroupDetail) GetGroupInfo() *GroupInfo {
	if x != nil {
		return x.GroupInfo
	}
	return nil
}

func (x *GetGroupResp_GroupDetail) GetGradeLevel() []*GradeLevel {
	if x != nil {
		return x.GradeLevel
	}
	return nil
}

func (x *GetGroupResp_GroupDetail) GetClassInfoList() []*ClassFullInfo {
	if x != nil {
		return x.ClassInfoList
	}
	return nil
}

type ListPersonGroupResp_GroupItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	PersonList    []*PersonItem          `protobuf:"bytes,3,rep,name=person_list,json=personList,proto3" json:"person_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPersonGroupResp_GroupItem) Reset() {
	*x = ListPersonGroupResp_GroupItem{}
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPersonGroupResp_GroupItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPersonGroupResp_GroupItem) ProtoMessage() {}

func (x *ListPersonGroupResp_GroupItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPersonGroupResp_GroupItem.ProtoReflect.Descriptor instead.
func (*ListPersonGroupResp_GroupItem) Descriptor() ([]byte, []int) {
	return file_api_groupCheck_v1_group_check_proto_rawDescGZIP(), []int{20, 0}
}

func (x *ListPersonGroupResp_GroupItem) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *ListPersonGroupResp_GroupItem) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *ListPersonGroupResp_GroupItem) GetPersonList() []*PersonItem {
	if x != nil {
		return x.PersonList
	}
	return nil
}

type ListPositionGroupResp_GroupItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	PersonList    []*PersonItem          `protobuf:"bytes,3,rep,name=person_list,json=personList,proto3" json:"person_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPositionGroupResp_GroupItem) Reset() {
	*x = ListPositionGroupResp_GroupItem{}
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPositionGroupResp_GroupItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPositionGroupResp_GroupItem) ProtoMessage() {}

func (x *ListPositionGroupResp_GroupItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPositionGroupResp_GroupItem.ProtoReflect.Descriptor instead.
func (*ListPositionGroupResp_GroupItem) Descriptor() ([]byte, []int) {
	return file_api_groupCheck_v1_group_check_proto_rawDescGZIP(), []int{21, 0}
}

func (x *ListPositionGroupResp_GroupItem) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *ListPositionGroupResp_GroupItem) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *ListPositionGroupResp_GroupItem) GetPersonList() []*PersonItem {
	if x != nil {
		return x.PersonList
	}
	return nil
}

type ListClassGroupResp_GroupItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	ClassList     []*ClassItem           `protobuf:"bytes,3,rep,name=class_list,json=classList,proto3" json:"class_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClassGroupResp_GroupItem) Reset() {
	*x = ListClassGroupResp_GroupItem{}
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClassGroupResp_GroupItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClassGroupResp_GroupItem) ProtoMessage() {}

func (x *ListClassGroupResp_GroupItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_groupCheck_v1_group_check_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClassGroupResp_GroupItem.ProtoReflect.Descriptor instead.
func (*ListClassGroupResp_GroupItem) Descriptor() ([]byte, []int) {
	return file_api_groupCheck_v1_group_check_proto_rawDescGZIP(), []int{22, 0}
}

func (x *ListClassGroupResp_GroupItem) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *ListClassGroupResp_GroupItem) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *ListClassGroupResp_GroupItem) GetClassList() []*ClassItem {
	if x != nil {
		return x.ClassList
	}
	return nil
}

var File_api_groupCheck_v1_group_check_proto protoreflect.FileDescriptor

const file_api_groupCheck_v1_group_check_proto_rawDesc = "" +
	"\n" +
	"#api/groupCheck/v1/group_check.proto\x12\n" +
	"GroupCheck\x1a\x1cgoogle/api/annotations.proto\"e\n" +
	"\vStudentInfo\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12!\n" +
	"\fstudent_name\x18\x02 \x01(\tR\vstudentName\x12\x14\n" +
	"\x05check\x18\x03 \x01(\bR\x05check\"`\n" +
	"\x0eClassBasicInfo\x12\x19\n" +
	"\bclass_id\x18\x01 \x01(\tR\aclassId\x12\x1d\n" +
	"\n" +
	"class_name\x18\x02 \x01(\tR\tclassName\x12\x14\n" +
	"\x05check\x18\x03 \x01(\bR\x05check\"|\n" +
	"\vSubjectInfo\x12!\n" +
	"\fsubject_name\x18\x01 \x01(\tR\vsubjectName\x12\x14\n" +
	"\x05check\x18\x02 \x01(\bR\x05check\x124\n" +
	"\aclasses\x18\x03 \x03(\v2\x1a.GroupCheck.ClassBasicInfoR\aclasses\"r\n" +
	"\n" +
	"GradeLevel\x12\x19\n" +
	"\bgrade_id\x18\x01 \x01(\tR\agradeId\x12\x14\n" +
	"\x05check\x18\x02 \x01(\bR\x05check\x123\n" +
	"\bsubjects\x18\x03 \x03(\v2\x17.GroupCheck.SubjectInfoR\bsubjects\"\xbc\x01\n" +
	"\rClassFullInfo\x12\x19\n" +
	"\bgrade_id\x18\x01 \x01(\tR\agradeId\x12!\n" +
	"\fsubject_name\x18\x02 \x01(\tR\vsubjectName\x12\x19\n" +
	"\bclass_id\x18\x03 \x01(\tR\aclassId\x12\x1d\n" +
	"\n" +
	"class_name\x18\x04 \x01(\tR\tclassName\x123\n" +
	"\bstudents\x18\x05 \x03(\v2\x17.GroupCheck.StudentInfoR\bstudents\"a\n" +
	"\tGroupInfo\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x05R\agroupId\x12\x1d\n" +
	"\n" +
	"group_name\x18\x02 \x01(\tR\tgroupName\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\x05R\bcategory\"N\n" +
	"\n" +
	"PersonItem\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12!\n" +
	"\fstudent_name\x18\x02 \x01(\tR\vstudentName\"E\n" +
	"\tClassItem\x12\x19\n" +
	"\bclass_id\x18\x01 \x01(\tR\aclassId\x12\x1d\n" +
	"\n" +
	"class_name\x18\x02 \x01(\tR\tclassName\"\xaa\x01\n" +
	"\rStudentDetail\x12\x19\n" +
	"\bgrade_id\x18\x01 \x01(\tR\agradeId\x12!\n" +
	"\fsubject_name\x18\x02 \x01(\tR\vsubjectName\x12\x19\n" +
	"\bclass_id\x18\x03 \x01(\tR\aclassId\x12!\n" +
	"\fstudent_name\x18\x04 \x01(\tR\vstudentName\x12\x1d\n" +
	"\n" +
	"student_id\x18\x05 \x01(\tR\tstudentId\"(\n" +
	"\vGetGroupReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x05R\agroupId\"\xc7\x02\n" +
	"\fGetGroupResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12G\n" +
	"\fgroup_detail\x18\x03 \x01(\v2$.GroupCheck.GetGroupResp.GroupDetailR\vgroupDetail\x1a\xbf\x01\n" +
	"\vGroupDetail\x124\n" +
	"\n" +
	"group_info\x18\x01 \x01(\v2\x15.GroupCheck.GroupInfoR\tgroupInfo\x127\n" +
	"\vgrade_level\x18\x02 \x03(\v2\x16.GroupCheck.GradeLevelR\n" +
	"gradeLevel\x12A\n" +
	"\x0fclass_info_list\x18\x03 \x03(\v2\x19.GroupCheck.ClassFullInfoR\rclassInfoList\".\n" +
	"\x11GetClassDetailReq\x12\x19\n" +
	"\bclass_id\x18\x01 \x01(\tR\aclassId\"t\n" +
	"\x12GetClassDetailResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x128\n" +
	"\n" +
	"class_info\x18\x03 \x01(\v2\x19.GroupCheck.ClassFullInfoR\tclassInfo\"5\n" +
	"\x10SearchStudentReq\x12!\n" +
	"\fstudent_name\x18\x01 \x01(\tR\vstudentName\"p\n" +
	"\x11SearchStudentResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\x04data\x18\x03 \x03(\v2\x19.GroupCheck.StudentDetailR\x04data\"\x16\n" +
	"\x14GetGradeClassTreeReq\"\x16\n" +
	"\x14GetPersonalGroupsReq\"\x13\n" +
	"\x11GetClassGroupsReq\"\x16\n" +
	"\x14GetPositionGroupsReq\"i\n" +
	"\x15GetGradeClassTreeResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12*\n" +
	"\x04data\x18\x03 \x03(\v2\x16.GroupCheck.GradeLevelR\x04data\"\xe8\x01\n" +
	"\x13ListPersonGroupResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12=\n" +
	"\x04data\x18\x02 \x03(\v2).GroupCheck.ListPersonGroupResp.GroupItemR\x04data\x1a~\n" +
	"\tGroupItem\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x05R\agroupId\x12\x1d\n" +
	"\n" +
	"group_name\x18\x02 \x01(\tR\tgroupName\x127\n" +
	"\vperson_list\x18\x03 \x03(\v2\x16.GroupCheck.PersonItemR\n" +
	"personList\"\xec\x01\n" +
	"\x15ListPositionGroupResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12?\n" +
	"\x04data\x18\x02 \x03(\v2+.GroupCheck.ListPositionGroupResp.GroupItemR\x04data\x1a~\n" +
	"\tGroupItem\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x05R\agroupId\x12\x1d\n" +
	"\n" +
	"group_name\x18\x02 \x01(\tR\tgroupName\x127\n" +
	"\vperson_list\x18\x03 \x03(\v2\x16.GroupCheck.PersonItemR\n" +
	"personList\"\xe3\x01\n" +
	"\x12ListClassGroupResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12<\n" +
	"\x04data\x18\x02 \x03(\v2(.GroupCheck.ListClassGroupResp.GroupItemR\x04data\x1a{\n" +
	"\tGroupItem\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x05R\agroupId\x12\x1d\n" +
	"\n" +
	"group_name\x18\x02 \x01(\tR\tgroupName\x124\n" +
	"\n" +
	"class_list\x18\x03 \x03(\v2\x15.GroupCheck.ClassItemR\tclassList2\xa2\x06\n" +
	"\n" +
	"GroupCheck\x12X\n" +
	"\bGetGroup\x12\x17.GroupCheck.GetGroupReq\x1a\x18.GroupCheck.GetGroupResp\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/group/details\x12q\n" +
	"\x0eGetClassDetail\x12\x1d.GroupCheck.GetClassDetailReq\x1a\x1e.GroupCheck.GetClassDetailResp\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/group/create/class/info\x12u\n" +
	"\rSearchStudent\x12\x1c.GroupCheck.SearchStudentReq\x1a\x1d.GroupCheck.SearchStudentResp\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/group/create/student/search\x12}\n" +
	"\x11GetGradeClassTree\x12 .GroupCheck.GetGradeClassTreeReq\x1a!.GroupCheck.GetGradeClassTreeResp\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/group/create/class/list\x12r\n" +
	"\x0fListPersonGroup\x12 .GroupCheck.GetPersonalGroupsReq\x1a\x1f.GroupCheck.ListPersonGroupResp\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/group/list/personal\x12q\n" +
	"\fListJobGroup\x12 .GroupCheck.GetPositionGroupsReq\x1a!.GroupCheck.ListPositionGroupResp\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/group/list/position\x12j\n" +
	"\x0eListClassGroup\x12\x1d.GroupCheck.GetClassGroupsReq\x1a\x1e.GroupCheck.ListClassGroupResp\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/group/list/classB6Z4ArgoNavisV1/GroupCheck/api/groupCheck/v1;group_checkb\x06proto3"

var (
	file_api_groupCheck_v1_group_check_proto_rawDescOnce sync.Once
	file_api_groupCheck_v1_group_check_proto_rawDescData []byte
)

func file_api_groupCheck_v1_group_check_proto_rawDescGZIP() []byte {
	file_api_groupCheck_v1_group_check_proto_rawDescOnce.Do(func() {
		file_api_groupCheck_v1_group_check_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_groupCheck_v1_group_check_proto_rawDesc), len(file_api_groupCheck_v1_group_check_proto_rawDesc)))
	})
	return file_api_groupCheck_v1_group_check_proto_rawDescData
}

var file_api_groupCheck_v1_group_check_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_api_groupCheck_v1_group_check_proto_goTypes = []any{
	(*StudentInfo)(nil),                     // 0: GroupCheck.StudentInfo
	(*ClassBasicInfo)(nil),                  // 1: GroupCheck.ClassBasicInfo
	(*SubjectInfo)(nil),                     // 2: GroupCheck.SubjectInfo
	(*GradeLevel)(nil),                      // 3: GroupCheck.GradeLevel
	(*ClassFullInfo)(nil),                   // 4: GroupCheck.ClassFullInfo
	(*GroupInfo)(nil),                       // 5: GroupCheck.GroupInfo
	(*PersonItem)(nil),                      // 6: GroupCheck.PersonItem
	(*ClassItem)(nil),                       // 7: GroupCheck.ClassItem
	(*StudentDetail)(nil),                   // 8: GroupCheck.StudentDetail
	(*GetGroupReq)(nil),                     // 9: GroupCheck.GetGroupReq
	(*GetGroupResp)(nil),                    // 10: GroupCheck.GetGroupResp
	(*GetClassDetailReq)(nil),               // 11: GroupCheck.GetClassDetailReq
	(*GetClassDetailResp)(nil),              // 12: GroupCheck.GetClassDetailResp
	(*SearchStudentReq)(nil),                // 13: GroupCheck.SearchStudentReq
	(*SearchStudentResp)(nil),               // 14: GroupCheck.SearchStudentResp
	(*GetGradeClassTreeReq)(nil),            // 15: GroupCheck.GetGradeClassTreeReq
	(*GetPersonalGroupsReq)(nil),            // 16: GroupCheck.GetPersonalGroupsReq
	(*GetClassGroupsReq)(nil),               // 17: GroupCheck.GetClassGroupsReq
	(*GetPositionGroupsReq)(nil),            // 18: GroupCheck.GetPositionGroupsReq
	(*GetGradeClassTreeResp)(nil),           // 19: GroupCheck.GetGradeClassTreeResp
	(*ListPersonGroupResp)(nil),             // 20: GroupCheck.ListPersonGroupResp
	(*ListPositionGroupResp)(nil),           // 21: GroupCheck.ListPositionGroupResp
	(*ListClassGroupResp)(nil),              // 22: GroupCheck.ListClassGroupResp
	(*GetGroupResp_GroupDetail)(nil),        // 23: GroupCheck.GetGroupResp.GroupDetail
	(*ListPersonGroupResp_GroupItem)(nil),   // 24: GroupCheck.ListPersonGroupResp.GroupItem
	(*ListPositionGroupResp_GroupItem)(nil), // 25: GroupCheck.ListPositionGroupResp.GroupItem
	(*ListClassGroupResp_GroupItem)(nil),    // 26: GroupCheck.ListClassGroupResp.GroupItem
}
var file_api_groupCheck_v1_group_check_proto_depIdxs = []int32{
	1,  // 0: GroupCheck.SubjectInfo.classes:type_name -> GroupCheck.ClassBasicInfo
	2,  // 1: GroupCheck.GradeLevel.subjects:type_name -> GroupCheck.SubjectInfo
	0,  // 2: GroupCheck.ClassFullInfo.students:type_name -> GroupCheck.StudentInfo
	23, // 3: GroupCheck.GetGroupResp.group_detail:type_name -> GroupCheck.GetGroupResp.GroupDetail
	4,  // 4: GroupCheck.GetClassDetailResp.class_info:type_name -> GroupCheck.ClassFullInfo
	8,  // 5: GroupCheck.SearchStudentResp.data:type_name -> GroupCheck.StudentDetail
	3,  // 6: GroupCheck.GetGradeClassTreeResp.data:type_name -> GroupCheck.GradeLevel
	24, // 7: GroupCheck.ListPersonGroupResp.data:type_name -> GroupCheck.ListPersonGroupResp.GroupItem
	25, // 8: GroupCheck.ListPositionGroupResp.data:type_name -> GroupCheck.ListPositionGroupResp.GroupItem
	26, // 9: GroupCheck.ListClassGroupResp.data:type_name -> GroupCheck.ListClassGroupResp.GroupItem
	5,  // 10: GroupCheck.GetGroupResp.GroupDetail.group_info:type_name -> GroupCheck.GroupInfo
	3,  // 11: GroupCheck.GetGroupResp.GroupDetail.grade_level:type_name -> GroupCheck.GradeLevel
	4,  // 12: GroupCheck.GetGroupResp.GroupDetail.class_info_list:type_name -> GroupCheck.ClassFullInfo
	6,  // 13: GroupCheck.ListPersonGroupResp.GroupItem.person_list:type_name -> GroupCheck.PersonItem
	6,  // 14: GroupCheck.ListPositionGroupResp.GroupItem.person_list:type_name -> GroupCheck.PersonItem
	7,  // 15: GroupCheck.ListClassGroupResp.GroupItem.class_list:type_name -> GroupCheck.ClassItem
	9,  // 16: GroupCheck.GroupCheck.GetGroup:input_type -> GroupCheck.GetGroupReq
	11, // 17: GroupCheck.GroupCheck.GetClassDetail:input_type -> GroupCheck.GetClassDetailReq
	13, // 18: GroupCheck.GroupCheck.SearchStudent:input_type -> GroupCheck.SearchStudentReq
	15, // 19: GroupCheck.GroupCheck.GetGradeClassTree:input_type -> GroupCheck.GetGradeClassTreeReq
	16, // 20: GroupCheck.GroupCheck.ListPersonGroup:input_type -> GroupCheck.GetPersonalGroupsReq
	18, // 21: GroupCheck.GroupCheck.ListJobGroup:input_type -> GroupCheck.GetPositionGroupsReq
	17, // 22: GroupCheck.GroupCheck.ListClassGroup:input_type -> GroupCheck.GetClassGroupsReq
	10, // 23: GroupCheck.GroupCheck.GetGroup:output_type -> GroupCheck.GetGroupResp
	12, // 24: GroupCheck.GroupCheck.GetClassDetail:output_type -> GroupCheck.GetClassDetailResp
	14, // 25: GroupCheck.GroupCheck.SearchStudent:output_type -> GroupCheck.SearchStudentResp
	19, // 26: GroupCheck.GroupCheck.GetGradeClassTree:output_type -> GroupCheck.GetGradeClassTreeResp
	20, // 27: GroupCheck.GroupCheck.ListPersonGroup:output_type -> GroupCheck.ListPersonGroupResp
	21, // 28: GroupCheck.GroupCheck.ListJobGroup:output_type -> GroupCheck.ListPositionGroupResp
	22, // 29: GroupCheck.GroupCheck.ListClassGroup:output_type -> GroupCheck.ListClassGroupResp
	23, // [23:30] is the sub-list for method output_type
	16, // [16:23] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_api_groupCheck_v1_group_check_proto_init() }
func file_api_groupCheck_v1_group_check_proto_init() {
	if File_api_groupCheck_v1_group_check_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_groupCheck_v1_group_check_proto_rawDesc), len(file_api_groupCheck_v1_group_check_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_groupCheck_v1_group_check_proto_goTypes,
		DependencyIndexes: file_api_groupCheck_v1_group_check_proto_depIdxs,
		MessageInfos:      file_api_groupCheck_v1_group_check_proto_msgTypes,
	}.Build()
	File_api_groupCheck_v1_group_check_proto = out.File
	file_api_groupCheck_v1_group_check_proto_goTypes = nil
	file_api_groupCheck_v1_group_check_proto_depIdxs = nil
}
