// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: api/receipt/v1/receipt.proto

package receipt

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReceiptStyleColumn struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ReceiptColumnName string                 `protobuf:"bytes,1,opt,name=receiptColumnName,proto3" json:"receiptColumnName,omitempty"` // 单行收集栏标题
	SingleOption      int32                  `protobuf:"varint,2,opt,name=SingleOption,proto3" json:"SingleOption,omitempty"`          // 是否为单选：1=是，0=否，默认1
	OptionList        []string               `protobuf:"bytes,3,rep,name=optionList,proto3" json:"optionList,omitempty"`               // 可选项栏，如["离校", "不离校"] 或 ["upload_file"]
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReceiptStyleColumn) Reset() {
	*x = ReceiptStyleColumn{}
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiptStyleColumn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiptStyleColumn) ProtoMessage() {}

func (x *ReceiptStyleColumn) ProtoReflect() protoreflect.Message {
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiptStyleColumn.ProtoReflect.Descriptor instead.
func (*ReceiptStyleColumn) Descriptor() ([]byte, []int) {
	return file_api_receipt_v1_receipt_proto_rawDescGZIP(), []int{0}
}

func (x *ReceiptStyleColumn) GetReceiptColumnName() string {
	if x != nil {
		return x.ReceiptColumnName
	}
	return ""
}

func (x *ReceiptStyleColumn) GetSingleOption() int32 {
	if x != nil {
		return x.SingleOption
	}
	return 0
}

func (x *ReceiptStyleColumn) GetOptionList() []string {
	if x != nil {
		return x.OptionList
	}
	return nil
}

type ReceiptWriteColumn struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ReceiptColumnName string                 `protobuf:"bytes,1,opt,name=receiptColumnName,proto3" json:"receiptColumnName,omitempty"` // 对应老师格式单栏名称
	Options           []string               `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`                     // 学生选择的选项 / 填写内容 / 文件 URL
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReceiptWriteColumn) Reset() {
	*x = ReceiptWriteColumn{}
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiptWriteColumn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiptWriteColumn) ProtoMessage() {}

func (x *ReceiptWriteColumn) ProtoReflect() protoreflect.Message {
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiptWriteColumn.ProtoReflect.Descriptor instead.
func (*ReceiptWriteColumn) Descriptor() ([]byte, []int) {
	return file_api_receipt_v1_receipt_proto_rawDescGZIP(), []int{1}
}

func (x *ReceiptWriteColumn) GetReceiptColumnName() string {
	if x != nil {
		return x.ReceiptColumnName
	}
	return ""
}

func (x *ReceiptWriteColumn) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

// =========================
// 获取收集表格式请求参数定义
// =========================
type GetReceiptStyleReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ReceiptStyleId string                 `protobuf:"bytes,1,opt,name=receipt_style_id,json=receiptStyleId,proto3" json:"receipt_style_id,omitempty"` // 收集表格式 ID
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetReceiptStyleReq) Reset() {
	*x = GetReceiptStyleReq{}
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReceiptStyleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReceiptStyleReq) ProtoMessage() {}

func (x *GetReceiptStyleReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReceiptStyleReq.ProtoReflect.Descriptor instead.
func (*GetReceiptStyleReq) Descriptor() ([]byte, []int) {
	return file_api_receipt_v1_receipt_proto_rawDescGZIP(), []int{2}
}

func (x *GetReceiptStyleReq) GetReceiptStyleId() string {
	if x != nil {
		return x.ReceiptStyleId
	}
	return ""
}

// =========================
// 获取收集表格式响应参数定义
// =========================
type GetReceiptStyleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                                    // 状态码
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`                                       // 返回消息
	ReceiptStyle  []*ReceiptStyleColumn  `protobuf:"bytes,3,rep,name=receipt_style,json=receiptStyle,proto3" json:"receipt_style,omitempty"` // 收集表格式内容（字段名按你提供拼写）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReceiptStyleResp) Reset() {
	*x = GetReceiptStyleResp{}
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReceiptStyleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReceiptStyleResp) ProtoMessage() {}

func (x *GetReceiptStyleResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReceiptStyleResp.ProtoReflect.Descriptor instead.
func (*GetReceiptStyleResp) Descriptor() ([]byte, []int) {
	return file_api_receipt_v1_receipt_proto_rawDescGZIP(), []int{3}
}

func (x *GetReceiptStyleResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetReceiptStyleResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetReceiptStyleResp) GetReceiptStyle() []*ReceiptStyleColumn {
	if x != nil {
		return x.ReceiptStyle
	}
	return nil
}

// =========================
// 获取收集表填写内容请求参数定义
// =========================
type GetReceiptListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoticeId      int32                  `protobuf:"varint,1,opt,name=notice_id,json=noticeId,proto3" json:"notice_id,omitempty"` // 通知ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReceiptListReq) Reset() {
	*x = GetReceiptListReq{}
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReceiptListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReceiptListReq) ProtoMessage() {}

func (x *GetReceiptListReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReceiptListReq.ProtoReflect.Descriptor instead.
func (*GetReceiptListReq) Descriptor() ([]byte, []int) {
	return file_api_receipt_v1_receipt_proto_rawDescGZIP(), []int{4}
}

func (x *GetReceiptListReq) GetNoticeId() int32 {
	if x != nil {
		return x.NoticeId
	}
	return 0
}

// =========================
// 获取收集表填写内容响应参数定义
// =========================
type GetReceiptListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                                    // 状态码
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`                                       // 信息
	ReceiptStyle  []*ReceiptStyleColumn  `protobuf:"bytes,3,rep,name=receipt_style,json=receiptStyle,proto3" json:"receipt_style,omitempty"` // 教师设置的收集表样式
	ReceiptList   []*ReceiptWriteOne     `protobuf:"bytes,4,rep,name=receipt_list,json=receiptList,proto3" json:"receipt_list,omitempty"`    // 所有学生填写内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReceiptListResp) Reset() {
	*x = GetReceiptListResp{}
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReceiptListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReceiptListResp) ProtoMessage() {}

func (x *GetReceiptListResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReceiptListResp.ProtoReflect.Descriptor instead.
func (*GetReceiptListResp) Descriptor() ([]byte, []int) {
	return file_api_receipt_v1_receipt_proto_rawDescGZIP(), []int{5}
}

func (x *GetReceiptListResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetReceiptListResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetReceiptListResp) GetReceiptStyle() []*ReceiptStyleColumn {
	if x != nil {
		return x.ReceiptStyle
	}
	return nil
}

func (x *GetReceiptListResp) GetReceiptList() []*ReceiptWriteOne {
	if x != nil {
		return x.ReceiptList
	}
	return nil
}

type ReceiptWriteOne struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StudentId      string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`                  // 学号
	ReceiptWriteId string                 `protobuf:"bytes,2,opt,name=receipt_write_id,json=receiptWriteId,proto3" json:"receipt_write_id,omitempty"` // 填写ID，用于后续打回
	Class          string                 `protobuf:"bytes,3,opt,name=class,proto3" json:"class,omitempty"`                                           // 班级编号
	StudentName    string                 `protobuf:"bytes,4,opt,name=student_name,json=studentName,proto3" json:"student_name,omitempty"`            // 学生姓名
	WriteTime      string                 `protobuf:"bytes,5,opt,name=write_time,json=writeTime,proto3" json:"write_time,omitempty"`                  // 填写时间（建议格式：ISO8601）
	ReceiptWrite   []*ReceiptWriteColumn  `protobuf:"bytes,6,rep,name=receipt_write,json=receiptWrite,proto3" json:"receipt_write,omitempty"`         // 各个学生填写的每一项数据
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReceiptWriteOne) Reset() {
	*x = ReceiptWriteOne{}
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiptWriteOne) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiptWriteOne) ProtoMessage() {}

func (x *ReceiptWriteOne) ProtoReflect() protoreflect.Message {
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiptWriteOne.ProtoReflect.Descriptor instead.
func (*ReceiptWriteOne) Descriptor() ([]byte, []int) {
	return file_api_receipt_v1_receipt_proto_rawDescGZIP(), []int{6}
}

func (x *ReceiptWriteOne) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *ReceiptWriteOne) GetReceiptWriteId() string {
	if x != nil {
		return x.ReceiptWriteId
	}
	return ""
}

func (x *ReceiptWriteOne) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *ReceiptWriteOne) GetStudentName() string {
	if x != nil {
		return x.StudentName
	}
	return ""
}

func (x *ReceiptWriteOne) GetWriteTime() string {
	if x != nil {
		return x.WriteTime
	}
	return ""
}

func (x *ReceiptWriteOne) GetReceiptWrite() []*ReceiptWriteColumn {
	if x != nil {
		return x.ReceiptWrite
	}
	return nil
}

type GetReceiptDownloadUrlReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoticeId      int32                  `protobuf:"varint,1,opt,name=notice_id,json=noticeId,proto3" json:"notice_id,omitempty"` // 通知ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReceiptDownloadUrlReq) Reset() {
	*x = GetReceiptDownloadUrlReq{}
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReceiptDownloadUrlReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReceiptDownloadUrlReq) ProtoMessage() {}

func (x *GetReceiptDownloadUrlReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReceiptDownloadUrlReq.ProtoReflect.Descriptor instead.
func (*GetReceiptDownloadUrlReq) Descriptor() ([]byte, []int) {
	return file_api_receipt_v1_receipt_proto_rawDescGZIP(), []int{7}
}

func (x *GetReceiptDownloadUrlReq) GetNoticeId() int32 {
	if x != nil {
		return x.NoticeId
	}
	return 0
}

type ReceiptWriteExcel struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ReceiptWriteExcelName string                 `protobuf:"bytes,1,opt,name=receipt_write_excel_name,json=receiptWriteExcelName,proto3" json:"receipt_write_excel_name,omitempty"` // 文件名
	ReceiptWriteExcelUrl  string                 `protobuf:"bytes,2,opt,name=receipt_write_excel_url,json=receiptWriteExcelUrl,proto3" json:"receipt_write_excel_url,omitempty"`    // 下载链接
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ReceiptWriteExcel) Reset() {
	*x = ReceiptWriteExcel{}
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiptWriteExcel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiptWriteExcel) ProtoMessage() {}

func (x *ReceiptWriteExcel) ProtoReflect() protoreflect.Message {
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiptWriteExcel.ProtoReflect.Descriptor instead.
func (*ReceiptWriteExcel) Descriptor() ([]byte, []int) {
	return file_api_receipt_v1_receipt_proto_rawDescGZIP(), []int{8}
}

func (x *ReceiptWriteExcel) GetReceiptWriteExcelName() string {
	if x != nil {
		return x.ReceiptWriteExcelName
	}
	return ""
}

func (x *ReceiptWriteExcel) GetReceiptWriteExcelUrl() string {
	if x != nil {
		return x.ReceiptWriteExcelUrl
	}
	return ""
}

type GetReceiptDownloadUrlResp struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Code              int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                                                     // 状态码
	Msg               string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`                                                        // 提示信息
	ReceiptWriteExcel *ReceiptWriteExcel     `protobuf:"bytes,3,opt,name=receipt_write_excel,json=receiptWriteExcel,proto3" json:"receipt_write_excel,omitempty"` // 下载信息对象
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetReceiptDownloadUrlResp) Reset() {
	*x = GetReceiptDownloadUrlResp{}
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReceiptDownloadUrlResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReceiptDownloadUrlResp) ProtoMessage() {}

func (x *GetReceiptDownloadUrlResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReceiptDownloadUrlResp.ProtoReflect.Descriptor instead.
func (*GetReceiptDownloadUrlResp) Descriptor() ([]byte, []int) {
	return file_api_receipt_v1_receipt_proto_rawDescGZIP(), []int{9}
}

func (x *GetReceiptDownloadUrlResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetReceiptDownloadUrlResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetReceiptDownloadUrlResp) GetReceiptWriteExcel() *ReceiptWriteExcel {
	if x != nil {
		return x.ReceiptWriteExcel
	}
	return nil
}

// 请求参数，传 receipt_write_id
type GetReceiptWriteSingleReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ReceiptWriteId string                 `protobuf:"bytes,1,opt,name=receipt_write_id,json=receiptWriteId,proto3" json:"receipt_write_id,omitempty"` // 收集表填写id，必填
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetReceiptWriteSingleReq) Reset() {
	*x = GetReceiptWriteSingleReq{}
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReceiptWriteSingleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReceiptWriteSingleReq) ProtoMessage() {}

func (x *GetReceiptWriteSingleReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReceiptWriteSingleReq.ProtoReflect.Descriptor instead.
func (*GetReceiptWriteSingleReq) Descriptor() ([]byte, []int) {
	return file_api_receipt_v1_receipt_proto_rawDescGZIP(), []int{10}
}

func (x *GetReceiptWriteSingleReq) GetReceiptWriteId() string {
	if x != nil {
		return x.ReceiptWriteId
	}
	return ""
}

// 响应参数
type GetReceiptWriteSingleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                                    // 状态码，比如200成功
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`                                       // 提示信息
	ReceiptWrite  []*ReceiptWriteColumn  `protobuf:"bytes,3,rep,name=receipt_write,json=receiptWrite,proto3" json:"receipt_write,omitempty"` // 填写详情列表，复用已有类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReceiptWriteSingleResp) Reset() {
	*x = GetReceiptWriteSingleResp{}
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReceiptWriteSingleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReceiptWriteSingleResp) ProtoMessage() {}

func (x *GetReceiptWriteSingleResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReceiptWriteSingleResp.ProtoReflect.Descriptor instead.
func (*GetReceiptWriteSingleResp) Descriptor() ([]byte, []int) {
	return file_api_receipt_v1_receipt_proto_rawDescGZIP(), []int{11}
}

func (x *GetReceiptWriteSingleResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetReceiptWriteSingleResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetReceiptWriteSingleResp) GetReceiptWrite() []*ReceiptWriteColumn {
	if x != nil {
		return x.ReceiptWrite
	}
	return nil
}

// =========================
// 创建收集表格式请求参数
// =========================
type CreateStyleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReceiptStyle  []*ReceiptStyleColumn  `protobuf:"bytes,1,rep,name=receipt_style,json=receiptStyle,proto3" json:"receipt_style,omitempty"` // 各行收集表格式汇总
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStyleReq) Reset() {
	*x = CreateStyleReq{}
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStyleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStyleReq) ProtoMessage() {}

func (x *CreateStyleReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStyleReq.ProtoReflect.Descriptor instead.
func (*CreateStyleReq) Descriptor() ([]byte, []int) {
	return file_api_receipt_v1_receipt_proto_rawDescGZIP(), []int{12}
}

func (x *CreateStyleReq) GetReceiptStyle() []*ReceiptStyleColumn {
	if x != nil {
		return x.ReceiptStyle
	}
	return nil
}

// =========================
// 返回参数
// =========================
type CreateStyleResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Code           int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                                            // 响应码
	Msg            string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`                                               // 提示信息
	ReceiptStyleId string                 `protobuf:"bytes,3,opt,name=receipt_style_id,json=receiptStyleId,proto3" json:"receipt_style_id,omitempty"` // 创建后的收集表格式ID
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateStyleResp) Reset() {
	*x = CreateStyleResp{}
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStyleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStyleResp) ProtoMessage() {}

func (x *CreateStyleResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStyleResp.ProtoReflect.Descriptor instead.
func (*CreateStyleResp) Descriptor() ([]byte, []int) {
	return file_api_receipt_v1_receipt_proto_rawDescGZIP(), []int{13}
}

func (x *CreateStyleResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateStyleResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CreateStyleResp) GetReceiptStyleId() string {
	if x != nil {
		return x.ReceiptStyleId
	}
	return ""
}

// ===============================
// 填收集表请求参数定义
// ===============================
type CreateReplyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoticeId      int32                  `protobuf:"varint,1,opt,name=notice_id,json=noticeId,proto3" json:"notice_id,omitempty"`            // 通知 ID
	ReceiptWrite  []*ReceiptWriteColumn  `protobuf:"bytes,2,rep,name=receipt_write,json=receiptWrite,proto3" json:"receipt_write,omitempty"` // 学生填写内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReplyReq) Reset() {
	*x = CreateReplyReq{}
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReplyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReplyReq) ProtoMessage() {}

func (x *CreateReplyReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReplyReq.ProtoReflect.Descriptor instead.
func (*CreateReplyReq) Descriptor() ([]byte, []int) {
	return file_api_receipt_v1_receipt_proto_rawDescGZIP(), []int{14}
}

func (x *CreateReplyReq) GetNoticeId() int32 {
	if x != nil {
		return x.NoticeId
	}
	return 0
}

func (x *CreateReplyReq) GetReceiptWrite() []*ReceiptWriteColumn {
	if x != nil {
		return x.ReceiptWrite
	}
	return nil
}

// ===============================
// 返回参数定义
// ===============================
type CreateReplyResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Code           int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                                            // 状态码
	Msg            string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`                                               // 提示信息
	ReceiptWriteId string                 `protobuf:"bytes,3,opt,name=receipt_write_id,json=receiptWriteId,proto3" json:"receipt_write_id,omitempty"` // 填写记录 ID（唯一标识）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateReplyResp) Reset() {
	*x = CreateReplyResp{}
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReplyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReplyResp) ProtoMessage() {}

func (x *CreateReplyResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReplyResp.ProtoReflect.Descriptor instead.
func (*CreateReplyResp) Descriptor() ([]byte, []int) {
	return file_api_receipt_v1_receipt_proto_rawDescGZIP(), []int{15}
}

func (x *CreateReplyResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateReplyResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CreateReplyResp) GetReceiptWriteId() string {
	if x != nil {
		return x.ReceiptWriteId
	}
	return ""
}

// ========================
// 修改收集表填写内容请求参数定义
// ========================
type ChangeReceiptReplyReq struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ReceiptWriteId     string                 `protobuf:"bytes,1,opt,name=receipt_write_id,json=receiptWriteId,proto3" json:"receipt_write_id,omitempty"`             // 学生曾经填写的收集表 ID
	ReceiptStyleId     string                 `protobuf:"bytes,2,opt,name=receipt_style_id,json=receiptStyleId,proto3" json:"receipt_style_id,omitempty"`             // 收集表格式 ID
	ReceiptWriteChange []*ReceiptWriteColumn  `protobuf:"bytes,3,rep,name=receipt_write_change,json=receiptWriteChange,proto3" json:"receipt_write_change,omitempty"` // 修改后的填写内容
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ChangeReceiptReplyReq) Reset() {
	*x = ChangeReceiptReplyReq{}
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeReceiptReplyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeReceiptReplyReq) ProtoMessage() {}

func (x *ChangeReceiptReplyReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeReceiptReplyReq.ProtoReflect.Descriptor instead.
func (*ChangeReceiptReplyReq) Descriptor() ([]byte, []int) {
	return file_api_receipt_v1_receipt_proto_rawDescGZIP(), []int{16}
}

func (x *ChangeReceiptReplyReq) GetReceiptWriteId() string {
	if x != nil {
		return x.ReceiptWriteId
	}
	return ""
}

func (x *ChangeReceiptReplyReq) GetReceiptStyleId() string {
	if x != nil {
		return x.ReceiptStyleId
	}
	return ""
}

func (x *ChangeReceiptReplyReq) GetReceiptWriteChange() []*ReceiptWriteColumn {
	if x != nil {
		return x.ReceiptWriteChange
	}
	return nil
}

// =========================
// 修改收集表填写内容响应参数定义
// =========================
type ChangeReceiptReplyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 返回状态码
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`    // 提示信息，如"修改成功"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeReceiptReplyResp) Reset() {
	*x = ChangeReceiptReplyResp{}
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeReceiptReplyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeReceiptReplyResp) ProtoMessage() {}

func (x *ChangeReceiptReplyResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_receipt_v1_receipt_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeReceiptReplyResp.ProtoReflect.Descriptor instead.
func (*ChangeReceiptReplyResp) Descriptor() ([]byte, []int) {
	return file_api_receipt_v1_receipt_proto_rawDescGZIP(), []int{17}
}

func (x *ChangeReceiptReplyResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ChangeReceiptReplyResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_api_receipt_v1_receipt_proto protoreflect.FileDescriptor

const file_api_receipt_v1_receipt_proto_rawDesc = "" +
	"\n" +
	"\x1capi/receipt/v1/receipt.proto\x12\aReceipt\x1a\x1cgoogle/api/annotations.proto\"\x86\x01\n" +
	"\x12ReceiptStyleColumn\x12,\n" +
	"\x11receiptColumnName\x18\x01 \x01(\tR\x11receiptColumnName\x12\"\n" +
	"\fSingleOption\x18\x02 \x01(\x05R\fSingleOption\x12\x1e\n" +
	"\n" +
	"optionList\x18\x03 \x03(\tR\n" +
	"optionList\"\\\n" +
	"\x12ReceiptWriteColumn\x12,\n" +
	"\x11receiptColumnName\x18\x01 \x01(\tR\x11receiptColumnName\x12\x18\n" +
	"\aoptions\x18\x02 \x03(\tR\aoptions\">\n" +
	"\x12GetReceiptStyleReq\x12(\n" +
	"\x10receipt_style_id\x18\x01 \x01(\tR\x0ereceiptStyleId\"}\n" +
	"\x13GetReceiptStyleResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12@\n" +
	"\rreceipt_style\x18\x03 \x03(\v2\x1b.Receipt.ReceiptStyleColumnR\freceiptStyle\"0\n" +
	"\x11GetReceiptListReq\x12\x1b\n" +
	"\tnotice_id\x18\x01 \x01(\x05R\bnoticeId\"\xb9\x01\n" +
	"\x12GetReceiptListResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12@\n" +
	"\rreceipt_style\x18\x03 \x03(\v2\x1b.Receipt.ReceiptStyleColumnR\freceiptStyle\x12;\n" +
	"\freceipt_list\x18\x04 \x03(\v2\x18.Receipt.ReceiptWriteOneR\vreceiptList\"\xf4\x01\n" +
	"\x0fReceiptWriteOne\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12(\n" +
	"\x10receipt_write_id\x18\x02 \x01(\tR\x0ereceiptWriteId\x12\x14\n" +
	"\x05class\x18\x03 \x01(\tR\x05class\x12!\n" +
	"\fstudent_name\x18\x04 \x01(\tR\vstudentName\x12\x1d\n" +
	"\n" +
	"write_time\x18\x05 \x01(\tR\twriteTime\x12@\n" +
	"\rreceipt_write\x18\x06 \x03(\v2\x1b.Receipt.ReceiptWriteColumnR\freceiptWrite\"7\n" +
	"\x18GetReceiptDownloadUrlReq\x12\x1b\n" +
	"\tnotice_id\x18\x01 \x01(\x05R\bnoticeId\"\x83\x01\n" +
	"\x11ReceiptWriteExcel\x127\n" +
	"\x18receipt_write_excel_name\x18\x01 \x01(\tR\x15receiptWriteExcelName\x125\n" +
	"\x17receipt_write_excel_url\x18\x02 \x01(\tR\x14receiptWriteExcelUrl\"\x8d\x01\n" +
	"\x19GetReceiptDownloadUrlResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12J\n" +
	"\x13receipt_write_excel\x18\x03 \x01(\v2\x1a.Receipt.ReceiptWriteExcelR\x11receiptWriteExcel\"D\n" +
	"\x18GetReceiptWriteSingleReq\x12(\n" +
	"\x10receipt_write_id\x18\x01 \x01(\tR\x0ereceiptWriteId\"\x83\x01\n" +
	"\x19GetReceiptWriteSingleResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12@\n" +
	"\rreceipt_write\x18\x03 \x03(\v2\x1b.Receipt.ReceiptWriteColumnR\freceiptWrite\"R\n" +
	"\x0eCreateStyleReq\x12@\n" +
	"\rreceipt_style\x18\x01 \x03(\v2\x1b.Receipt.ReceiptStyleColumnR\freceiptStyle\"a\n" +
	"\x0fCreateStyleResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12(\n" +
	"\x10receipt_style_id\x18\x03 \x01(\tR\x0ereceiptStyleId\"o\n" +
	"\x0eCreateReplyReq\x12\x1b\n" +
	"\tnotice_id\x18\x01 \x01(\x05R\bnoticeId\x12@\n" +
	"\rreceipt_write\x18\x02 \x03(\v2\x1b.Receipt.ReceiptWriteColumnR\freceiptWrite\"a\n" +
	"\x0fCreateReplyResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12(\n" +
	"\x10receipt_write_id\x18\x03 \x01(\tR\x0ereceiptWriteId\"\xba\x01\n" +
	"\x15ChangeReceiptReplyReq\x12(\n" +
	"\x10receipt_write_id\x18\x01 \x01(\tR\x0ereceiptWriteId\x12(\n" +
	"\x10receipt_style_id\x18\x02 \x01(\tR\x0ereceiptStyleId\x12M\n" +
	"\x14receipt_write_change\x18\x03 \x03(\v2\x1b.Receipt.ReceiptWriteColumnR\x12receiptWriteChange\">\n" +
	"\x16ChangeReceiptReplyResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg2\xc3\x06\n" +
	"\aReceipt\x12r\n" +
	"\x0fGetReceiptStyle\x12\x1b.Receipt.GetReceiptStyleReq\x1a\x1c.Receipt.GetReceiptStyleResp\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/receipt/check/teacher/style\x12f\n" +
	"\x0eGetReceiptList\x12\x1a.Receipt.GetReceiptListReq\x1a\x1b.Receipt.GetReceiptListResp\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/receipt/check/list\x12\x88\x01\n" +
	"\x15GetReceiptDownloadUrl\x12!.Receipt.GetReceiptDownloadUrlReq\x1a\".Receipt.GetReceiptDownloadUrlResp\"(\x82\xd3\xe4\x93\x02\"\x12 /receipt/check/list/download_url\x12}\n" +
	"\x15GetReceiptWriteSingle\x12!.Receipt.GetReceiptWriteSingleReq\x1a\".Receipt.GetReceiptWriteSingleResp\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/receipt/check/Single\x12h\n" +
	"\vCreateStyle\x12\x17.Receipt.CreateStyleReq\x1a\x18.Receipt.CreateStyleResp\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/receipt/write/create/style\x12i\n" +
	"\vCreateReply\x12\x17.Receipt.CreateReplyReq\x1a\x18.Receipt.CreateReplyResp\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/receipt/write/student/reply\x12}\n" +
	"\x12ChangeReceiptReply\x12\x1e.Receipt.ChangeReceiptReplyReq\x1a\x1f.Receipt.ChangeReceiptReplyResp\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/receipt/write/change/replyB Z\x1eReceipt/api/receipt/v1;receiptb\x06proto3"

var (
	file_api_receipt_v1_receipt_proto_rawDescOnce sync.Once
	file_api_receipt_v1_receipt_proto_rawDescData []byte
)

func file_api_receipt_v1_receipt_proto_rawDescGZIP() []byte {
	file_api_receipt_v1_receipt_proto_rawDescOnce.Do(func() {
		file_api_receipt_v1_receipt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_receipt_v1_receipt_proto_rawDesc), len(file_api_receipt_v1_receipt_proto_rawDesc)))
	})
	return file_api_receipt_v1_receipt_proto_rawDescData
}

var file_api_receipt_v1_receipt_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_api_receipt_v1_receipt_proto_goTypes = []any{
	(*ReceiptStyleColumn)(nil),        // 0: Receipt.ReceiptStyleColumn
	(*ReceiptWriteColumn)(nil),        // 1: Receipt.ReceiptWriteColumn
	(*GetReceiptStyleReq)(nil),        // 2: Receipt.GetReceiptStyleReq
	(*GetReceiptStyleResp)(nil),       // 3: Receipt.GetReceiptStyleResp
	(*GetReceiptListReq)(nil),         // 4: Receipt.GetReceiptListReq
	(*GetReceiptListResp)(nil),        // 5: Receipt.GetReceiptListResp
	(*ReceiptWriteOne)(nil),           // 6: Receipt.ReceiptWriteOne
	(*GetReceiptDownloadUrlReq)(nil),  // 7: Receipt.GetReceiptDownloadUrlReq
	(*ReceiptWriteExcel)(nil),         // 8: Receipt.ReceiptWriteExcel
	(*GetReceiptDownloadUrlResp)(nil), // 9: Receipt.GetReceiptDownloadUrlResp
	(*GetReceiptWriteSingleReq)(nil),  // 10: Receipt.GetReceiptWriteSingleReq
	(*GetReceiptWriteSingleResp)(nil), // 11: Receipt.GetReceiptWriteSingleResp
	(*CreateStyleReq)(nil),            // 12: Receipt.CreateStyleReq
	(*CreateStyleResp)(nil),           // 13: Receipt.CreateStyleResp
	(*CreateReplyReq)(nil),            // 14: Receipt.CreateReplyReq
	(*CreateReplyResp)(nil),           // 15: Receipt.CreateReplyResp
	(*ChangeReceiptReplyReq)(nil),     // 16: Receipt.ChangeReceiptReplyReq
	(*ChangeReceiptReplyResp)(nil),    // 17: Receipt.ChangeReceiptReplyResp
}
var file_api_receipt_v1_receipt_proto_depIdxs = []int32{
	0,  // 0: Receipt.GetReceiptStyleResp.receipt_style:type_name -> Receipt.ReceiptStyleColumn
	0,  // 1: Receipt.GetReceiptListResp.receipt_style:type_name -> Receipt.ReceiptStyleColumn
	6,  // 2: Receipt.GetReceiptListResp.receipt_list:type_name -> Receipt.ReceiptWriteOne
	1,  // 3: Receipt.ReceiptWriteOne.receipt_write:type_name -> Receipt.ReceiptWriteColumn
	8,  // 4: Receipt.GetReceiptDownloadUrlResp.receipt_write_excel:type_name -> Receipt.ReceiptWriteExcel
	1,  // 5: Receipt.GetReceiptWriteSingleResp.receipt_write:type_name -> Receipt.ReceiptWriteColumn
	0,  // 6: Receipt.CreateStyleReq.receipt_style:type_name -> Receipt.ReceiptStyleColumn
	1,  // 7: Receipt.CreateReplyReq.receipt_write:type_name -> Receipt.ReceiptWriteColumn
	1,  // 8: Receipt.ChangeReceiptReplyReq.receipt_write_change:type_name -> Receipt.ReceiptWriteColumn
	2,  // 9: Receipt.Receipt.GetReceiptStyle:input_type -> Receipt.GetReceiptStyleReq
	4,  // 10: Receipt.Receipt.GetReceiptList:input_type -> Receipt.GetReceiptListReq
	7,  // 11: Receipt.Receipt.GetReceiptDownloadUrl:input_type -> Receipt.GetReceiptDownloadUrlReq
	10, // 12: Receipt.Receipt.GetReceiptWriteSingle:input_type -> Receipt.GetReceiptWriteSingleReq
	12, // 13: Receipt.Receipt.CreateStyle:input_type -> Receipt.CreateStyleReq
	14, // 14: Receipt.Receipt.CreateReply:input_type -> Receipt.CreateReplyReq
	16, // 15: Receipt.Receipt.ChangeReceiptReply:input_type -> Receipt.ChangeReceiptReplyReq
	3,  // 16: Receipt.Receipt.GetReceiptStyle:output_type -> Receipt.GetReceiptStyleResp
	5,  // 17: Receipt.Receipt.GetReceiptList:output_type -> Receipt.GetReceiptListResp
	9,  // 18: Receipt.Receipt.GetReceiptDownloadUrl:output_type -> Receipt.GetReceiptDownloadUrlResp
	11, // 19: Receipt.Receipt.GetReceiptWriteSingle:output_type -> Receipt.GetReceiptWriteSingleResp
	13, // 20: Receipt.Receipt.CreateStyle:output_type -> Receipt.CreateStyleResp
	15, // 21: Receipt.Receipt.CreateReply:output_type -> Receipt.CreateReplyResp
	17, // 22: Receipt.Receipt.ChangeReceiptReply:output_type -> Receipt.ChangeReceiptReplyResp
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_receipt_v1_receipt_proto_init() }
func file_api_receipt_v1_receipt_proto_init() {
	if File_api_receipt_v1_receipt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_receipt_v1_receipt_proto_rawDesc), len(file_api_receipt_v1_receipt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_receipt_v1_receipt_proto_goTypes,
		DependencyIndexes: file_api_receipt_v1_receipt_proto_depIdxs,
		MessageInfos:      file_api_receipt_v1_receipt_proto_msgTypes,
	}.Build()
	File_api_receipt_v1_receipt_proto = out.File
	file_api_receipt_v1_receipt_proto_goTypes = nil
	file_api_receipt_v1_receipt_proto_depIdxs = nil
}
