// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: api/stuNoticeCheck/v1/stuNoticeCheck.proto

package stuNoticeCheck

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取已完成通知详情的通知ID的请求消息
type GetfinishNoticeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoticeId      int32                  `protobuf:"varint,1,opt,name=notice_id,json=noticeId,proto3" json:"notice_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetfinishNoticeReq) Reset() {
	*x = GetfinishNoticeReq{}
	mi := &file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetfinishNoticeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetfinishNoticeReq) ProtoMessage() {}

func (x *GetfinishNoticeReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetfinishNoticeReq.ProtoReflect.Descriptor instead.
func (*GetfinishNoticeReq) Descriptor() ([]byte, []int) {
	return file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_rawDescGZIP(), []int{0}
}

func (x *GetfinishNoticeReq) GetNoticeId() int32 {
	if x != nil {
		return x.NoticeId
	}
	return 0
}

// 获取已完成通知详情的响应消息
type GetfinishNoticeResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Code           int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg            string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	NoticeId       int32                  `protobuf:"varint,3,opt,name=notice_id,json=noticeId,proto3" json:"notice_id,omitempty"`
	Priority       string                 `protobuf:"bytes,4,opt,name=priority,proto3" json:"priority,omitempty"`
	NoticeTitle    string                 `protobuf:"bytes,5,opt,name=notice_title,json=noticeTitle,proto3" json:"notice_title,omitempty"`
	NoticeContext  string                 `protobuf:"bytes,6,opt,name=notice_context,json=noticeContext,proto3" json:"notice_context,omitempty"`
	Deadline       string                `protobuf:"bytes,7,opt,name=deadline,proto3" json:"deadline,omitempty"`
	FileList       []*FileInfo           `protobuf:"bytes,8,rep,name=file_list,json=fileList,proto3" json:"file_list,omitempty"`
	Status         string                `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	ReceiptStyleId string                `protobuf:"bytes,10,opt,name=receipt_style_id,json=receiptStyleId,proto3" json:"receipt_style_id,omitempty"`
	ReceiptStyle   []*ReceiptStyleColumn `protobuf:"bytes,11,rep,name=receipt_style,json=receiptStyle,proto3" json:"receipt_style,omitempty"`
	ReceiptWriteId string                `protobuf:"bytes,12,opt,name=receipt_write_id,json=receiptWriteId,proto3" json:"receipt_write_id,omitempty"`
	ReceiptWrite   []*ReceiptWriteColumn `protobuf:"bytes,13,rep,name=receipt_write,json=receiptWrite,proto3" json:"receipt_write,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetfinishNoticeResp) Reset() {
	*x = GetfinishNoticeResp{}
	mi := &file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetfinishNoticeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetfinishNoticeResp) ProtoMessage() {}

func (x *GetfinishNoticeResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetfinishNoticeResp.ProtoReflect.Descriptor instead.
func (*GetfinishNoticeResp) Descriptor() ([]byte, []int) {
	return file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_rawDescGZIP(), []int{1}
}

func (x *GetfinishNoticeResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetfinishNoticeResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetfinishNoticeResp) GetNoticeId() int32 {
	if x != nil {
		return x.NoticeId
	}
	return 0
}

func (x *GetfinishNoticeResp) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *GetfinishNoticeResp) GetNoticeTitle() string {
	if x != nil {
		return x.NoticeTitle
	}
	return ""
}

func (x *GetfinishNoticeResp) GetNoticeContext() string {
	if x != nil {
		return x.NoticeContext
	}
	return ""
}

func (x *GetfinishNoticeResp) GetDeadline() string {
	if x != nil {
		return x.Deadline
	}
	return ""
}

func (x *GetfinishNoticeResp) GetFileList() []*FileInfo {
	if x != nil {
		return x.FileList
	}
	return nil
}

func (x *GetfinishNoticeResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetfinishNoticeResp) GetReceiptStyleId() string {
	if x != nil {
		return x.ReceiptStyleId
	}
	return ""
}

func (x *GetfinishNoticeResp) GetReceiptStyle() []*ReceiptStyleColumn {
	if x != nil {
		return x.ReceiptStyle
	}
	return nil
}

func (x *GetfinishNoticeResp) GetReceiptWriteId() string {
	if x != nil {
		return x.ReceiptWriteId
	}
	return ""
}

func (x *GetfinishNoticeResp) GetReceiptWrite() []*ReceiptWriteColumn {
	if x != nil {
		return x.ReceiptWrite
	}
	return nil
}

// 获取未完成通知详情的通知ID的请求消息
type GetUnfinishedNoticeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoticeId      int32                  `protobuf:"varint,1,opt,name=notice_id,json=noticeId,proto3" json:"notice_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnfinishedNoticeReq) Reset() {
	*x = GetUnfinishedNoticeReq{}
	mi := &file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnfinishedNoticeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnfinishedNoticeReq) ProtoMessage() {}

func (x *GetUnfinishedNoticeReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnfinishedNoticeReq.ProtoReflect.Descriptor instead.
func (*GetUnfinishedNoticeReq) Descriptor() ([]byte, []int) {
	return file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_rawDescGZIP(), []int{2}
}

func (x *GetUnfinishedNoticeReq) GetNoticeId() int32 {
	if x != nil {
		return x.NoticeId
	}
	return 0
}

// 包含未完成通知详情的响应消息
type GetUnfinishedNoticeResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Code           int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg            string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	NoticeId       int32                  `protobuf:"varint,3,opt,name=notice_id,json=noticeId,proto3" json:"notice_id,omitempty"`
	Priority       string                 `protobuf:"bytes,4,opt,name=priority,proto3" json:"priority,omitempty"`
	NoticeTitle    string                 `protobuf:"bytes,5,opt,name=notice_title,json=noticeTitle,proto3" json:"notice_title,omitempty"`
	NoticeContext  string                 `protobuf:"bytes,6,opt,name=notice_context,json=noticeContext,proto3" json:"notice_context,omitempty"`
	Deadline       string                 `protobuf:"bytes,7,opt,name=deadline,proto3" json:"deadline,omitempty"`
	State          string                `protobuf:"bytes,8,opt,name=state,proto3" json:"state,omitempty"`
	FileList       []*FileInfo           `protobuf:"bytes,9,rep,name=file_list,json=fileList,proto3" json:"file_list,omitempty"`
	ReceiptStyleId string                `protobuf:"bytes,10,opt,name=receipt_style_id,json=receiptStyleId,proto3" json:"receipt_style_id,omitempty"`
	ReceiptStyle   []*ReceiptStyleColumn `protobuf:"bytes,11,rep,name=receipt_style,json=receiptStyle,proto3" json:"receipt_style,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetUnfinishedNoticeResp) Reset() {
	*x = GetUnfinishedNoticeResp{}
	mi := &file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnfinishedNoticeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnfinishedNoticeResp) ProtoMessage() {}

func (x *GetUnfinishedNoticeResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnfinishedNoticeResp.ProtoReflect.Descriptor instead.
func (*GetUnfinishedNoticeResp) Descriptor() ([]byte, []int) {
	return file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_rawDescGZIP(), []int{3}
}

func (x *GetUnfinishedNoticeResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetUnfinishedNoticeResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetUnfinishedNoticeResp) GetNoticeId() int32 {
	if x != nil {
		return x.NoticeId
	}
	return 0
}

func (x *GetUnfinishedNoticeResp) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *GetUnfinishedNoticeResp) GetNoticeTitle() string {
	if x != nil {
		return x.NoticeTitle
	}
	return ""
}

func (x *GetUnfinishedNoticeResp) GetNoticeContext() string {
	if x != nil {
		return x.NoticeContext
	}
	return ""
}

func (x *GetUnfinishedNoticeResp) GetDeadline() string {
	if x != nil {
		return x.Deadline
	}
	return ""
}

func (x *GetUnfinishedNoticeResp) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *GetUnfinishedNoticeResp) GetFileList() []*FileInfo {
	if x != nil {
		return x.FileList
	}
	return nil
}

func (x *GetUnfinishedNoticeResp) GetReceiptStyleId() string {
	if x != nil {
		return x.ReceiptStyleId
	}
	return ""
}

func (x *GetUnfinishedNoticeResp) GetReceiptStyle() []*ReceiptStyleColumn {
	if x != nil {
		return x.ReceiptStyle
	}
	return nil
}

// 包含搜索关键字的请求消息
type SearchNoticeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchNoticeReq) Reset() {
	*x = SearchNoticeReq{}
	mi := &file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchNoticeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchNoticeReq) ProtoMessage() {}

func (x *SearchNoticeReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchNoticeReq.ProtoReflect.Descriptor instead.
func (*SearchNoticeReq) Descriptor() ([]byte, []int) {
	return file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_rawDescGZIP(), []int{4}
}

func (x *SearchNoticeReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

// 包含搜索结果的响应消息
type SearchNoticeResp struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Code             int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg              string              `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	SearchNoticeList []*SearchNoticeItem `protobuf:"bytes,3,rep,name=search_notice_list,json=searchNoticeList,proto3" json:"search_notice_list,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SearchNoticeResp) Reset() {
	*x = SearchNoticeResp{}
	mi := &file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchNoticeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchNoticeResp) ProtoMessage() {}

func (x *SearchNoticeResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchNoticeResp.ProtoReflect.Descriptor instead.
func (*SearchNoticeResp) Descriptor() ([]byte, []int) {
	return file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_rawDescGZIP(), []int{5}
}

func (x *SearchNoticeResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SearchNoticeResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SearchNoticeResp) GetSearchNoticeList() []*SearchNoticeItem {
	if x != nil {
		return x.SearchNoticeList
	}
	return nil
}

// 搜索结果项
type SearchNoticeItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoticeId      int32                  `protobuf:"varint,1,opt,name=notice_id,json=noticeId,proto3" json:"notice_id,omitempty"`
	Priority      string                 `protobuf:"bytes,2,opt,name=priority,proto3" json:"priority,omitempty"`
	NoticeTitle   string                 `protobuf:"bytes,3,opt,name=notice_title,json=noticeTitle,proto3" json:"notice_title,omitempty"`
	Deadline      string                 `protobuf:"bytes,4,opt,name=deadline,proto3" json:"deadline,omitempty"`
	RemainTime    string                 `protobuf:"bytes,5,opt,name=remain_time,json=remainTime,proto3" json:"remain_time,omitempty"`
	NoticeContext string                 `protobuf:"bytes,6,opt,name=notice_context,json=noticeContext,proto3" json:"notice_context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchNoticeItem) Reset() {
	*x = SearchNoticeItem{}
	mi := &file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchNoticeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchNoticeItem) ProtoMessage() {}

func (x *SearchNoticeItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchNoticeItem.ProtoReflect.Descriptor instead.
func (*SearchNoticeItem) Descriptor() ([]byte, []int) {
	return file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_rawDescGZIP(), []int{6}
}

func (x *SearchNoticeItem) GetNoticeId() int32 {
	if x != nil {
		return x.NoticeId
	}
	return 0
}

func (x *SearchNoticeItem) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *SearchNoticeItem) GetNoticeTitle() string {
	if x != nil {
		return x.NoticeTitle
	}
	return ""
}

func (x *SearchNoticeItem) GetDeadline() string {
	if x != nil {
		return x.Deadline
	}
	return ""
}

func (x *SearchNoticeItem) GetRemainTime() string {
	if x != nil {
		return x.RemainTime
	}
	return ""
}

func (x *SearchNoticeItem) GetNoticeContext() string {
	if x != nil {
		return x.NoticeContext
	}
	return ""
}

// 获取已归档通知列表的请求消息（空请求）
type GetArchivedNoticeListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArchivedNoticeListReq) Reset() {
	*x = GetArchivedNoticeListReq{}
	mi := &file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArchivedNoticeListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArchivedNoticeListReq) ProtoMessage() {}

func (x *GetArchivedNoticeListReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArchivedNoticeListReq.ProtoReflect.Descriptor instead.
func (*GetArchivedNoticeListReq) Descriptor() ([]byte, []int) {
	return file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_rawDescGZIP(), []int{7}
}

// 包含已归档通知列表的响应消息
type GetArchivedNoticeListResp struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Code             int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg              string                `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	FinishNoticeList []*ArchivedNoticeItem `protobuf:"bytes,3,rep,name=finish_notice_list,json=finishNoticeList,proto3" json:"finish_notice_list,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetArchivedNoticeListResp) Reset() {
	*x = GetArchivedNoticeListResp{}
	mi := &file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArchivedNoticeListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArchivedNoticeListResp) ProtoMessage() {}

func (x *GetArchivedNoticeListResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArchivedNoticeListResp.ProtoReflect.Descriptor instead.
func (*GetArchivedNoticeListResp) Descriptor() ([]byte, []int) {
	return file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_rawDescGZIP(), []int{8}
}

func (x *GetArchivedNoticeListResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetArchivedNoticeListResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetArchivedNoticeListResp) GetFinishNoticeList() []*ArchivedNoticeItem {
	if x != nil {
		return x.FinishNoticeList
	}
	return nil
}

// 已归档通知项
type ArchivedNoticeItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoticeId      int32                  `protobuf:"varint,1,opt,name=notice_id,json=noticeId,proto3" json:"notice_id,omitempty"`
	Priority      string                 `protobuf:"bytes,2,opt,name=priority,proto3" json:"priority,omitempty"`
	NoticeTitle   string                 `protobuf:"bytes,3,opt,name=notice_title,json=noticeTitle,proto3" json:"notice_title,omitempty"`
	Deadline      string                 `protobuf:"bytes,4,opt,name=deadline,proto3" json:"deadline,omitempty"`
	RemainTime    string                 `protobuf:"bytes,5,opt,name=remain_time,json=remainTime,proto3" json:"remain_time,omitempty"`
	NoticeContext string                 `protobuf:"bytes,6,opt,name=notice_context,json=noticeContext,proto3" json:"notice_context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchivedNoticeItem) Reset() {
	*x = ArchivedNoticeItem{}
	mi := &file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchivedNoticeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchivedNoticeItem) ProtoMessage() {}

func (x *ArchivedNoticeItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchivedNoticeItem.ProtoReflect.Descriptor instead.
func (*ArchivedNoticeItem) Descriptor() ([]byte, []int) {
	return file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_rawDescGZIP(), []int{9}
}

func (x *ArchivedNoticeItem) GetNoticeId() int32 {
	if x != nil {
		return x.NoticeId
	}
	return 0
}

func (x *ArchivedNoticeItem) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *ArchivedNoticeItem) GetNoticeTitle() string {
	if x != nil {
		return x.NoticeTitle
	}
	return ""
}

func (x *ArchivedNoticeItem) GetDeadline() string {
	if x != nil {
		return x.Deadline
	}
	return ""
}

func (x *ArchivedNoticeItem) GetRemainTime() string {
	if x != nil {
		return x.RemainTime
	}
	return ""
}

func (x *ArchivedNoticeItem) GetNoticeContext() string {
	if x != nil {
		return x.NoticeContext
	}
	return ""
}

// 获取未完成通知列表的请求消息（空请求）
type GetUnfinishedNoticeListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnfinishedNoticeListReq) Reset() {
	*x = GetUnfinishedNoticeListReq{}
	mi := &file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnfinishedNoticeListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnfinishedNoticeListReq) ProtoMessage() {}

func (x *GetUnfinishedNoticeListReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnfinishedNoticeListReq.ProtoReflect.Descriptor instead.
func (*GetUnfinishedNoticeListReq) Descriptor() ([]byte, []int) {
	return file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_rawDescGZIP(), []int{10}
}

// 包含未完成通知列表的响应消息
type GetUnfinishedNoticeListResp struct {
	state              protoimpl.MessageState  `protogen:"open.v1"`
	Code               int32                   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                string                  `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	UnfinishNoticeList []*UnfinishedNoticeItem `protobuf:"bytes,3,rep,name=unfinish_notice_list,json=unfinishNoticeList,proto3" json:"unfinish_notice_list,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetUnfinishedNoticeListResp) Reset() {
	*x = GetUnfinishedNoticeListResp{}
	mi := &file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnfinishedNoticeListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnfinishedNoticeListResp) ProtoMessage() {}

func (x *GetUnfinishedNoticeListResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnfinishedNoticeListResp.ProtoReflect.Descriptor instead.
func (*GetUnfinishedNoticeListResp) Descriptor() ([]byte, []int) {
	return file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_rawDescGZIP(), []int{11}
}

func (x *GetUnfinishedNoticeListResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetUnfinishedNoticeListResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetUnfinishedNoticeListResp) GetUnfinishNoticeList() []*UnfinishedNoticeItem {
	if x != nil {
		return x.UnfinishNoticeList
	}
	return nil
}

// 未完成通知项
type UnfinishedNoticeItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoticeId      int32                  `protobuf:"varint,1,opt,name=notice_id,json=noticeId,proto3" json:"notice_id,omitempty"`
	Priority      string                 `protobuf:"bytes,2,opt,name=priority,proto3" json:"priority,omitempty"`
	NoticeTitle   string                 `protobuf:"bytes,3,opt,name=notice_title,json=noticeTitle,proto3" json:"notice_title,omitempty"`
	Deadline      string                 `protobuf:"bytes,4,opt,name=deadline,proto3" json:"deadline,omitempty"`
	RemainTime    string                 `protobuf:"bytes,5,opt,name=remain_time,json=remainTime,proto3" json:"remain_time,omitempty"`
	NoticeContext string                 `protobuf:"bytes,6,opt,name=notice_context,json=noticeContext,proto3" json:"notice_context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfinishedNoticeItem) Reset() {
	*x = UnfinishedNoticeItem{}
	mi := &file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfinishedNoticeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfinishedNoticeItem) ProtoMessage() {}

func (x *UnfinishedNoticeItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfinishedNoticeItem.ProtoReflect.Descriptor instead.
func (*UnfinishedNoticeItem) Descriptor() ([]byte, []int) {
	return file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_rawDescGZIP(), []int{12}
}

func (x *UnfinishedNoticeItem) GetNoticeId() int32 {
	if x != nil {
		return x.NoticeId
	}
	return 0
}

func (x *UnfinishedNoticeItem) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *UnfinishedNoticeItem) GetNoticeTitle() string {
	if x != nil {
		return x.NoticeTitle
	}
	return ""
}

func (x *UnfinishedNoticeItem) GetDeadline() string {
	if x != nil {
		return x.Deadline
	}
	return ""
}

func (x *UnfinishedNoticeItem) GetRemainTime() string {
	if x != nil {
		return x.RemainTime
	}
	return ""
}

func (x *UnfinishedNoticeItem) GetNoticeContext() string {
	if x != nil {
		return x.NoticeContext
	}
	return ""
}

// 文件信息
type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileUrl       string                 `protobuf:"bytes,2,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_rawDescGZIP(), []int{13}
}

func (x *FileInfo) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FileInfo) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

// 收集表格式定义
type ReceiptStyleColumn struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ReceiptColumnName string                 `protobuf:"bytes,1,opt,name=receiptColumnName,proto3" json:"receiptColumnName,omitempty"`
	SingleOption      int32                  `protobuf:"varint,2,opt,name=SingleOption,proto3" json:"SingleOption,omitempty"`
	OptionList        []string               `protobuf:"bytes,3,rep,name=optionList,proto3" json:"optionList,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReceiptStyleColumn) Reset() {
	*x = ReceiptStyleColumn{}
	mi := &file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiptStyleColumn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiptStyleColumn) ProtoMessage() {}

func (x *ReceiptStyleColumn) ProtoReflect() protoreflect.Message {
	mi := &file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiptStyleColumn.ProtoReflect.Descriptor instead.
func (*ReceiptStyleColumn) Descriptor() ([]byte, []int) {
	return file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_rawDescGZIP(), []int{14}
}

func (x *ReceiptStyleColumn) GetReceiptColumnName() string {
	if x != nil {
		return x.ReceiptColumnName
	}
	return ""
}

func (x *ReceiptStyleColumn) GetSingleOption() int32 {
	if x != nil {
		return x.SingleOption
	}
	return 0
}

func (x *ReceiptStyleColumn) GetOptionList() []string {
	if x != nil {
		return x.OptionList
	}
	return nil
}

// 收集表填写内容
type ReceiptWriteColumn struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ReceiptColumnName string                 `protobuf:"bytes,1,opt,name=receiptColumnName,proto3" json:"receiptColumnName,omitempty"`
	Options           []string               `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReceiptWriteColumn) Reset() {
	*x = ReceiptWriteColumn{}
	mi := &file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiptWriteColumn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiptWriteColumn) ProtoMessage() {}

func (x *ReceiptWriteColumn) ProtoReflect() protoreflect.Message {
	mi := &file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiptWriteColumn.ProtoReflect.Descriptor instead.
func (*ReceiptWriteColumn) Descriptor() ([]byte, []int) {
	return file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_rawDescGZIP(), []int{15}
}

func (x *ReceiptWriteColumn) GetReceiptColumnName() string {
	if x != nil {
		return x.ReceiptColumnName
	}
	return ""
}

func (x *ReceiptWriteColumn) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

var File_api_stuNoticeCheck_v1_stuNoticeCheck_proto protoreflect.FileDescriptor

const file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_rawDesc = "" +
	"\n" +
	"*api/stuNoticeCheck/v1/stuNoticeCheck.proto\x12\x0eStuNoticeCheck\x1a\x1cgoogle/api/annotations.proto\"1\n" +
	"\x12GetfinishNoticeReq\x12\x1b\n" +
	"\tnotice_id\x18\x01 \x01(\x05R\bnoticeId\"\x8f\x04\n" +
	"\x13GetfinishNoticeResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1b\n" +
	"\tnotice_id\x18\x03 \x01(\x05R\bnoticeId\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\tR\bpriority\x12!\n" +
	"\fnotice_title\x18\x05 \x01(\tR\vnoticeTitle\x12%\n" +
	"\x0enotice_context\x18\x06 \x01(\tR\rnoticeContext\x12\x1a\n" +
	"\bdeadline\x18\a \x01(\tR\bdeadline\x125\n" +
	"\tfile_list\x18\b \x03(\v2\x18.StuNoticeCheck.FileInfoR\bfileList\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12(\n" +
	"\x10receipt_style_id\x18\n" +
	" \x01(\tR\x0ereceiptStyleId\x12G\n" +
	"\rreceipt_style\x18\v \x03(\v2\".StuNoticeCheck.ReceiptStyleColumnR\freceiptStyle\x12(\n" +
	"\x10receipt_write_id\x18\f \x01(\tR\x0ereceiptWriteId\x12G\n" +
	"\rreceipt_write\x18\r \x03(\v2\".StuNoticeCheck.ReceiptWriteColumnR\freceiptWrite\"5\n" +
	"\x16GetUnfinishedNoticeReq\x12\x1b\n" +
	"\tnotice_id\x18\x01 \x01(\x05R\bnoticeId\"\x9e\x03\n" +
	"\x17GetUnfinishedNoticeResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1b\n" +
	"\tnotice_id\x18\x03 \x01(\x05R\bnoticeId\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\tR\bpriority\x12!\n" +
	"\fnotice_title\x18\x05 \x01(\tR\vnoticeTitle\x12%\n" +
	"\x0enotice_context\x18\x06 \x01(\tR\rnoticeContext\x12\x1a\n" +
	"\bdeadline\x18\a \x01(\tR\bdeadline\x12\x14\n" +
	"\x05state\x18\b \x01(\tR\x05state\x125\n" +
	"\tfile_list\x18\t \x03(\v2\x18.StuNoticeCheck.FileInfoR\bfileList\x12(\n" +
	"\x10receipt_style_id\x18\n" +
	" \x01(\tR\x0ereceiptStyleId\x12G\n" +
	"\rreceipt_style\x18\v \x03(\v2\".StuNoticeCheck.ReceiptStyleColumnR\freceiptStyle\"+\n" +
	"\x0fSearchNoticeReq\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\"\x88\x01\n" +
	"\x10SearchNoticeResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12N\n" +
	"\x12search_notice_list\x18\x03 \x03(\v2 .StuNoticeCheck.SearchNoticeItemR\x10searchNoticeList\"\xd2\x01\n" +
	"\x10SearchNoticeItem\x12\x1b\n" +
	"\tnotice_id\x18\x01 \x01(\x05R\bnoticeId\x12\x1a\n" +
	"\bpriority\x18\x02 \x01(\tR\bpriority\x12!\n" +
	"\fnotice_title\x18\x03 \x01(\tR\vnoticeTitle\x12\x1a\n" +
	"\bdeadline\x18\x04 \x01(\tR\bdeadline\x12\x1f\n" +
	"\vremain_time\x18\x05 \x01(\tR\n" +
	"remainTime\x12%\n" +
	"\x0enotice_context\x18\x06 \x01(\tR\rnoticeContext\"\x1a\n" +
	"\x18GetArchivedNoticeListReq\"\x93\x01\n" +
	"\x19GetArchivedNoticeListResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12P\n" +
	"\x12finish_notice_list\x18\x03 \x03(\v2\".StuNoticeCheck.ArchivedNoticeItemR\x10finishNoticeList\"\xd4\x01\n" +
	"\x12ArchivedNoticeItem\x12\x1b\n" +
	"\tnotice_id\x18\x01 \x01(\x05R\bnoticeId\x12\x1a\n" +
	"\bpriority\x18\x02 \x01(\tR\bpriority\x12!\n" +
	"\fnotice_title\x18\x03 \x01(\tR\vnoticeTitle\x12\x1a\n" +
	"\bdeadline\x18\x04 \x01(\tR\bdeadline\x12\x1f\n" +
	"\vremain_time\x18\x05 \x01(\tR\n" +
	"remainTime\x12%\n" +
	"\x0enotice_context\x18\x06 \x01(\tR\rnoticeContext\"\x1c\n" +
	"\x1aGetUnfinishedNoticeListReq\"\x9b\x01\n" +
	"\x1bGetUnfinishedNoticeListResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12V\n" +
	"\x14unfinish_notice_list\x18\x03 \x03(\v2$.StuNoticeCheck.UnfinishedNoticeItemR\x12unfinishNoticeList\"\xd6\x01\n" +
	"\x14UnfinishedNoticeItem\x12\x1b\n" +
	"\tnotice_id\x18\x01 \x01(\x05R\bnoticeId\x12\x1a\n" +
	"\bpriority\x18\x02 \x01(\tR\bpriority\x12!\n" +
	"\fnotice_title\x18\x03 \x01(\tR\vnoticeTitle\x12\x1a\n" +
	"\bdeadline\x18\x04 \x01(\tR\bdeadline\x12\x1f\n" +
	"\vremain_time\x18\x05 \x01(\tR\n" +
	"remainTime\x12%\n" +
	"\x0enotice_context\x18\x06 \x01(\tR\rnoticeContext\"B\n" +
	"\bFileInfo\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x19\n" +
	"\bfile_url\x18\x02 \x01(\tR\afileUrl\"\x86\x01\n" +
	"\x12ReceiptStyleColumn\x12,\n" +
	"\x11receiptColumnName\x18\x01 \x01(\tR\x11receiptColumnName\x12\"\n" +
	"\fSingleOption\x18\x02 \x01(\x05R\fSingleOption\x12\x1e\n" +
	"\n" +
	"optionList\x18\x03 \x03(\tR\n" +
	"optionList\"\\\n" +
	"\x12ReceiptWriteColumn\x12,\n" +
	"\x11receiptColumnName\x18\x01 \x01(\tR\x11receiptColumnName\x12\x18\n" +
	"\aoptions\x18\x02 \x03(\tR\aoptions2\xd9\x05\n" +
	"\bStuCheck\x12\x89\x01\n" +
	"\tGetNotice\x12\".StuNoticeCheck.GetfinishNoticeReq\x1a#.StuNoticeCheck.GetfinishNoticeResp\"3\x82\xd3\xe4\x93\x02-\x12+/student/noitce/finifsh/details/{notice_id}\x12\x9c\x01\n" +
	"\x13GetUnfinishedNotice\x12&.StuNoticeCheck.GetUnfinishedNoticeReq\x1a'.StuNoticeCheck.GetUnfinishedNoticeResp\"4\x82\xd3\xe4\x93\x02.\x12,/student/notice/unfinish/details/{notice_id}\x12q\n" +
	"\fSearchNotice\x12\x1f.StuNoticeCheck.SearchNoticeReq\x1a .StuNoticeCheck.SearchNoticeResp\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/student/search/notice\x12\x92\x01\n" +
	"\x15GetArchivedNoticeList\x12(.StuNoticeCheck.GetArchivedNoticeListReq\x1a).StuNoticeCheck.GetArchivedNoticeListResp\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/student/notice/finfish/list\x12\x99\x01\n" +
	"\x17GetUnfinishedNoticeList\x12*.StuNoticeCheck.GetUnfinishedNoticeListReq\x1a+.StuNoticeCheck.GetUnfinishedNoticeListResp\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/student/notice/unfinish/listBAZ?ArgoNavisV3/TeaNoticeCheck/api/stuNoticeCheck/v1;stuNoticeCheckb\x06proto3"

var (
	file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_rawDescOnce sync.Once
	file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_rawDescData []byte
)

func file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_rawDescGZIP() []byte {
	file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_rawDescOnce.Do(func() {
		file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_rawDesc), len(file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_rawDesc)))
	})
	return file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_rawDescData
}

var file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_goTypes = []any{
	(*GetfinishNoticeReq)(nil),          // 0: StuNoticeCheck.GetfinishNoticeReq
	(*GetfinishNoticeResp)(nil),         // 1: StuNoticeCheck.GetfinishNoticeResp
	(*GetUnfinishedNoticeReq)(nil),      // 2: StuNoticeCheck.GetUnfinishedNoticeReq
	(*GetUnfinishedNoticeResp)(nil),     // 3: StuNoticeCheck.GetUnfinishedNoticeResp
	(*SearchNoticeReq)(nil),             // 4: StuNoticeCheck.SearchNoticeReq
	(*SearchNoticeResp)(nil),            // 5: StuNoticeCheck.SearchNoticeResp
	(*SearchNoticeItem)(nil),            // 6: StuNoticeCheck.SearchNoticeItem
	(*GetArchivedNoticeListReq)(nil),    // 7: StuNoticeCheck.GetArchivedNoticeListReq
	(*GetArchivedNoticeListResp)(nil),   // 8: StuNoticeCheck.GetArchivedNoticeListResp
	(*ArchivedNoticeItem)(nil),          // 9: StuNoticeCheck.ArchivedNoticeItem
	(*GetUnfinishedNoticeListReq)(nil),  // 10: StuNoticeCheck.GetUnfinishedNoticeListReq
	(*GetUnfinishedNoticeListResp)(nil), // 11: StuNoticeCheck.GetUnfinishedNoticeListResp
	(*UnfinishedNoticeItem)(nil),        // 12: StuNoticeCheck.UnfinishedNoticeItem
	(*FileInfo)(nil),                    // 13: StuNoticeCheck.FileInfo
	(*ReceiptStyleColumn)(nil),          // 14: StuNoticeCheck.ReceiptStyleColumn
	(*ReceiptWriteColumn)(nil),          // 15: StuNoticeCheck.ReceiptWriteColumn
}
var file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_depIdxs = []int32{
	13, // 0: StuNoticeCheck.GetfinishNoticeResp.file_list:type_name -> StuNoticeCheck.FileInfo
	14, // 1: StuNoticeCheck.GetfinishNoticeResp.receipt_style:type_name -> StuNoticeCheck.ReceiptStyleColumn
	15, // 2: StuNoticeCheck.GetfinishNoticeResp.receipt_write:type_name -> StuNoticeCheck.ReceiptWriteColumn
	13, // 3: StuNoticeCheck.GetUnfinishedNoticeResp.file_list:type_name -> StuNoticeCheck.FileInfo
	14, // 4: StuNoticeCheck.GetUnfinishedNoticeResp.receipt_style:type_name -> StuNoticeCheck.ReceiptStyleColumn
	6,  // 5: StuNoticeCheck.SearchNoticeResp.search_notice_list:type_name -> StuNoticeCheck.SearchNoticeItem
	9,  // 6: StuNoticeCheck.GetArchivedNoticeListResp.finish_notice_list:type_name -> StuNoticeCheck.ArchivedNoticeItem
	12, // 7: StuNoticeCheck.GetUnfinishedNoticeListResp.unfinish_notice_list:type_name -> StuNoticeCheck.UnfinishedNoticeItem
	0,  // 8: StuNoticeCheck.StuCheck.GetNotice:input_type -> StuNoticeCheck.GetfinishNoticeReq
	2,  // 9: StuNoticeCheck.StuCheck.GetUnfinishedNotice:input_type -> StuNoticeCheck.GetUnfinishedNoticeReq
	4,  // 10: StuNoticeCheck.StuCheck.SearchNotice:input_type -> StuNoticeCheck.SearchNoticeReq
	7,  // 11: StuNoticeCheck.StuCheck.GetArchivedNoticeList:input_type -> StuNoticeCheck.GetArchivedNoticeListReq
	10, // 12: StuNoticeCheck.StuCheck.GetUnfinishedNoticeList:input_type -> StuNoticeCheck.GetUnfinishedNoticeListReq
	1,  // 13: StuNoticeCheck.StuCheck.GetNotice:output_type -> StuNoticeCheck.GetfinishNoticeResp
	3,  // 14: StuNoticeCheck.StuCheck.GetUnfinishedNotice:output_type -> StuNoticeCheck.GetUnfinishedNoticeResp
	5,  // 15: StuNoticeCheck.StuCheck.SearchNotice:output_type -> StuNoticeCheck.SearchNoticeResp
	8,  // 16: StuNoticeCheck.StuCheck.GetArchivedNoticeList:output_type -> StuNoticeCheck.GetArchivedNoticeListResp
	11, // 17: StuNoticeCheck.StuCheck.GetUnfinishedNoticeList:output_type -> StuNoticeCheck.GetUnfinishedNoticeListResp
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_init() }
func file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_init() {
	if File_api_stuNoticeCheck_v1_stuNoticeCheck_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_rawDesc), len(file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_goTypes,
		DependencyIndexes: file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_depIdxs,
		MessageInfos:      file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_msgTypes,
	}.Build()
	File_api_stuNoticeCheck_v1_stuNoticeCheck_proto = out.File
	file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_goTypes = nil
	file_api_stuNoticeCheck_v1_stuNoticeCheck_proto_depIdxs = nil
}
