// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v6.31.1
// source: api/stuNoticeManage/v1/stuNoticeManage.proto

package stuNoticeManage

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationStuManageConfirmNotice = "/StuNoticeManage.StuManage/ConfirmNotice"

type StuManageHTTPServer interface {
	// ConfirmNotice 确认通知
	ConfirmNotice(context.Context, *ConfirmNoticeReq) (*ConfirmNoticeResp, error)
}

func RegisterStuManageHTTPServer(s *http.Server, srv StuManageHTTPServer) {
	r := s.Route("/")
	r.POST("/student/notice/confirm", _StuManage_ConfirmNotice0_HTTP_Handler(srv))
}

func _StuManage_ConfirmNotice0_HTTP_Handler(srv StuManageHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ConfirmNoticeReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStuManageConfirmNotice)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ConfirmNotice(ctx, req.(*ConfirmNoticeReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ConfirmNoticeResp)
		return ctx.Result(200, reply)
	}
}

type StuManageHTTPClient interface {
	ConfirmNotice(ctx context.Context, req *ConfirmNoticeReq, opts ...http.CallOption) (rsp *ConfirmNoticeResp, err error)
}

type StuManageHTTPClientImpl struct {
	cc *http.Client
}

func NewStuManageHTTPClient(client *http.Client) StuManageHTTPClient {
	return &StuManageHTTPClientImpl{client}
}

func (c *StuManageHTTPClientImpl) ConfirmNotice(ctx context.Context, in *ConfirmNoticeReq, opts ...http.CallOption) (*ConfirmNoticeResp, error) {
	var out ConfirmNoticeResp
	pattern := "/student/notice/confirm"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationStuManageConfirmNotice))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
