// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: api/stuNoticeManage/v1/stuNoticeManage.proto

package stuNoticeManage

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StuManage_ConfirmNotice_FullMethodName = "/StuNoticeManage.StuManage/ConfirmNotice"
)

// StuManageClient is the client API for StuManage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 学生端通知管理服务定义
type StuManageClient interface {
	// 确认通知
	ConfirmNotice(ctx context.Context, in *ConfirmNoticeReq, opts ...grpc.CallOption) (*ConfirmNoticeResp, error)
}

type stuManageClient struct {
	cc grpc.ClientConnInterface
}

func NewStuManageClient(cc grpc.ClientConnInterface) StuManageClient {
	return &stuManageClient{cc}
}

func (c *stuManageClient) ConfirmNotice(ctx context.Context, in *ConfirmNoticeReq, opts ...grpc.CallOption) (*ConfirmNoticeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmNoticeResp)
	err := c.cc.Invoke(ctx, StuManage_ConfirmNotice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StuManageServer is the server API for StuManage service.
// All implementations must embed UnimplementedStuManageServer
// for forward compatibility.
//
// 学生端通知管理服务定义
type StuManageServer interface {
	// 确认通知
	ConfirmNotice(context.Context, *ConfirmNoticeReq) (*ConfirmNoticeResp, error)
	mustEmbedUnimplementedStuManageServer()
}

// UnimplementedStuManageServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStuManageServer struct{}

func (UnimplementedStuManageServer) ConfirmNotice(context.Context, *ConfirmNoticeReq) (*ConfirmNoticeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmNotice not implemented")
}
func (UnimplementedStuManageServer) mustEmbedUnimplementedStuManageServer() {}
func (UnimplementedStuManageServer) testEmbeddedByValue()                   {}

// UnsafeStuManageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StuManageServer will
// result in compilation errors.
type UnsafeStuManageServer interface {
	mustEmbedUnimplementedStuManageServer()
}

func RegisterStuManageServer(s grpc.ServiceRegistrar, srv StuManageServer) {
	// If the following call pancis, it indicates UnimplementedStuManageServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StuManage_ServiceDesc, srv)
}

func _StuManage_ConfirmNotice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmNoticeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StuManageServer).ConfirmNotice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StuManage_ConfirmNotice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StuManageServer).ConfirmNotice(ctx, req.(*ConfirmNoticeReq))
	}
	return interceptor(ctx, in, info, handler)
}

// StuManage_ServiceDesc is the grpc.ServiceDesc for StuManage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StuManage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "StuNoticeManage.StuManage",
	HandlerType: (*StuManageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConfirmNotice",
			Handler:    _StuManage_ConfirmNotice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/stuNoticeManage/v1/stuNoticeManage.proto",
}
