// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: api/stuNoticeManage/v1/stuNoticeManage.proto

package stuNoticeManage

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 确认反馈的请求消息
type ConfirmNoticeReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NoticeId       int32                  `protobuf:"varint,1,opt,name=notice_id,json=noticeId,proto3" json:"notice_id,omitempty"`
	RecepitWriteId string                 `protobuf:"bytes,2,opt,name=recepit_write_id,json=recepitWriteId,proto3" json:"recepit_write_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConfirmNoticeReq) Reset() {
	*x = ConfirmNoticeReq{}
	mi := &file_api_stuNoticeManage_v1_stuNoticeManage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmNoticeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmNoticeReq) ProtoMessage() {}

func (x *ConfirmNoticeReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_stuNoticeManage_v1_stuNoticeManage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmNoticeReq.ProtoReflect.Descriptor instead.
func (*ConfirmNoticeReq) Descriptor() ([]byte, []int) {
	return file_api_stuNoticeManage_v1_stuNoticeManage_proto_rawDescGZIP(), []int{0}
}

func (x *ConfirmNoticeReq) GetNoticeId() int32 {
	if x != nil {
		return x.NoticeId
	}
	return 0
}

func (x *ConfirmNoticeReq) GetRecepitWriteId() string {
	if x != nil {
		return x.RecepitWriteId
	}
	return ""
}

// 确认反馈的响应消息
type ConfirmNoticeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmNoticeResp) Reset() {
	*x = ConfirmNoticeResp{}
	mi := &file_api_stuNoticeManage_v1_stuNoticeManage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmNoticeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmNoticeResp) ProtoMessage() {}

func (x *ConfirmNoticeResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_stuNoticeManage_v1_stuNoticeManage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmNoticeResp.ProtoReflect.Descriptor instead.
func (*ConfirmNoticeResp) Descriptor() ([]byte, []int) {
	return file_api_stuNoticeManage_v1_stuNoticeManage_proto_rawDescGZIP(), []int{1}
}

func (x *ConfirmNoticeResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ConfirmNoticeResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_api_stuNoticeManage_v1_stuNoticeManage_proto protoreflect.FileDescriptor

const file_api_stuNoticeManage_v1_stuNoticeManage_proto_rawDesc = "" +
	"\n" +
	",api/stuNoticeManage/v1/stuNoticeManage.proto\x12\x0fStuNoticeManage\x1a\x1cgoogle/api/annotations.proto\"Y\n" +
	"\x10ConfirmNoticeReq\x12\x1b\n" +
	"\tnotice_id\x18\x01 \x01(\x05R\bnoticeId\x12(\n" +
	"\x10recepit_write_id\x18\x02 \x01(\tR\x0erecepitWriteId\"9\n" +
	"\x11ConfirmNoticeResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg2\x87\x01\n" +
	"\tStuManage\x12z\n" +
	"\rConfirmNotice\x12!.StuNoticeManage.ConfirmNoticeReq\x1a\".StuNoticeManage.ConfirmNoticeResp\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/student/notice/confirmBDZBArgoNavisV3/StuNoticeManage/api/stuNoticeManage/v1;stuNoticeManageb\x06proto3"

var (
	file_api_stuNoticeManage_v1_stuNoticeManage_proto_rawDescOnce sync.Once
	file_api_stuNoticeManage_v1_stuNoticeManage_proto_rawDescData []byte
)

func file_api_stuNoticeManage_v1_stuNoticeManage_proto_rawDescGZIP() []byte {
	file_api_stuNoticeManage_v1_stuNoticeManage_proto_rawDescOnce.Do(func() {
		file_api_stuNoticeManage_v1_stuNoticeManage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_stuNoticeManage_v1_stuNoticeManage_proto_rawDesc), len(file_api_stuNoticeManage_v1_stuNoticeManage_proto_rawDesc)))
	})
	return file_api_stuNoticeManage_v1_stuNoticeManage_proto_rawDescData
}

var file_api_stuNoticeManage_v1_stuNoticeManage_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_stuNoticeManage_v1_stuNoticeManage_proto_goTypes = []any{
	(*ConfirmNoticeReq)(nil),  // 0: StuNoticeManage.ConfirmNoticeReq
	(*ConfirmNoticeResp)(nil), // 1: StuNoticeManage.ConfirmNoticeResp
}
var file_api_stuNoticeManage_v1_stuNoticeManage_proto_depIdxs = []int32{
	0, // 0: StuNoticeManage.StuManage.ConfirmNotice:input_type -> StuNoticeManage.ConfirmNoticeReq
	1, // 1: StuNoticeManage.StuManage.ConfirmNotice:output_type -> StuNoticeManage.ConfirmNoticeResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_stuNoticeManage_v1_stuNoticeManage_proto_init() }
func file_api_stuNoticeManage_v1_stuNoticeManage_proto_init() {
	if File_api_stuNoticeManage_v1_stuNoticeManage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_stuNoticeManage_v1_stuNoticeManage_proto_rawDesc), len(file_api_stuNoticeManage_v1_stuNoticeManage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_stuNoticeManage_v1_stuNoticeManage_proto_goTypes,
		DependencyIndexes: file_api_stuNoticeManage_v1_stuNoticeManage_proto_depIdxs,
		MessageInfos:      file_api_stuNoticeManage_v1_stuNoticeManage_proto_msgTypes,
	}.Build()
	File_api_stuNoticeManage_v1_stuNoticeManage_proto = out.File
	file_api_stuNoticeManage_v1_stuNoticeManage_proto_goTypes = nil
	file_api_stuNoticeManage_v1_stuNoticeManage_proto_depIdxs = nil
}
